#!/usr/bin/env python3
"""Dev-only: TECH v0.6 consumer audit for MonsterPal, MonsterStencil, BattleMagicPoints (and the
graphics base MonsterGfx) from the Rev 1 disassembly debug info. Writes
audits/enemy_consumers_v0.6.json (evidence) and data/enemy_relocation_v06.json (builder input).
usage: enemy_consumer_audit.py <ff6dis> <clean.sfc>"""
import sys, os, json
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "devtools"))
from dbgrefs import Dbg
dis, romp = sys.argv[1], sys.argv[2]
rom = open(romp, "rb").read()
D = Dbg(os.path.join(dis, "build/en/rom/ff6-en.dbg"))
REL = {   # name -> (symbol, old base, old end, record size, vanilla count)
    "MONSTER_PAL":         ("MonsterPal", 0xD27820, 0xD2A81F, 16, 768),
    "MONSTER_STENCIL":     ("MonsterStencil", 0xD2A820, 0xD2B223, None, None),
    "BATTLE_MAGIC_POINTS": ("BattleMagicPoints", 0xDFB400, 0xDFB5FF, 1, 512),
}
LONG = {0xAF, 0xBF, 0x8F, 0x9F, 0xCF, 0xDF, 0x2F, 0x3F, 0x0F, 0x1F, 0x4F, 0x5F, 0x6F, 0x7F, 0xEF, 0xFF}
ev, data = {}, {"_comment": "Generated by devtools/enemy_consumer_audit.py; every instruction is asserted against the clean Rev 1 ROM by the builder.", "tables": {}}
for name, (sym, base, end, rec, cnt) in REL.items():
    cons = []
    for s in D.syms_by_name[sym]:
        for r in s.get("ref", "").split("+"):
            if not r: continue
            lid = int(r); f, ln, txt = D.line_src(lid)
            if not any(p in f for p in ("src/battle/", "src/btlgfx/", "src/menu/")):
                continue
            for a, n in D.line_addrs(lid):
                b = rom[a - 0xC00000:a - 0xC00000 + n]
                t = txt.replace(" ", "")
                if n == 4 and b[0] in LONG:
                    op = b[1] | b[2] << 8 | b[3] << 16
                    if "bank_start" in txt:
                        kind, disp = "long_bank", 0
                        assert op == base & 0xFF0000, (name, hex(a))
                    else:
                        kind, disp = "long", op - base
                        assert 0 <= disp <= end - base, (name, hex(a))
                elif "#^" in t:
                    kind, disp = "imm_bank", 0
                    assert b[1] == base >> 16
                elif "#near" in txt:
                    kind = "imm_near"; v = b[1] | b[2] << 8; disp = v - (base & 0xFFFF)
                    assert 0 <= disp < 0x10
                else:
                    raise SystemExit(f"unclassified {name} {a:06X} {txt}")
                e = {"snes": f"{a:06X}", "bytes": b.hex(" ").upper(), "kind": kind, "disp": disp}
                if e not in cons:
                    cons.append(e)
                    ev.setdefault(name, []).append(dict(e, src=f"{f.lstrip('./')}:{ln}", text=txt.strip()))
    cons.sort(key=lambda e: e["snes"])
    data["tables"][name] = {"old_base": f"{base:06X}", "old_end": f"{end:06X}", "record_size": rec,
                            "vanilla_count": cnt, "consumers": cons}
# non-symbolic literal found by a source review of every MonsterStencil user (colosseum menu builds the
# stencil data pointer with a hard-coded bank byte): must move with the table.
MANUAL = {"MONSTER_STENCIL": [{"snes": "C3AFFD", "bytes": "A9 D2", "kind": "imm_bank", "disp": 0,
                               "manual": "src/menu/colosseum.asm:456 'lda #$d2' (stencil data bank literal)"}]}
for name, extra in MANUAL.items():
    for e in extra:
        a = int(e["snes"], 16)
        assert rom[a - 0xC00000:a - 0xC00000 + 2].hex(" ").upper() == e["bytes"]
        data["tables"][name]["consumers"].append(e)
        ev[name].append(dict(e, src=e["manual"], text="lda #$d2"))
    data["tables"][name]["consumers"].sort(key=lambda e: e["snes"])
gfx = []
for s in D.syms_by_name["MonsterGfx"]:
    for r in s.get("ref", "").split("+"):
        if not r: continue
        lid = int(r); f, ln, txt = D.line_src(lid)
        if not any(p in f for p in ("src/battle/", "src/btlgfx/", "src/menu/")):
            continue
        for a, n in D.line_addrs(lid):
            gfx.append({"snes": f"{a:06X}", "bytes": rom[a - 0xC00000:a - 0xC00000 + n].hex(" ").upper(), "src": f"{f.lstrip('./')}:{ln}", "text": txt.strip()})
ev["MONSTER_GFX_BASE_IMMEDIATES"] = gfx
json.dump({"tables": ev, "counts": {k: len(v) for k, v in ev.items()}},
          open(os.path.join(HERE, "audits", "enemy_consumers_v0.6.json"), "w"), indent=1)
json.dump(data, open(os.path.join(HERE, "data", "enemy_relocation_v06.json"), "w"), indent=1)
print({k: len(v) for k, v in ev.items()})
