#!/usr/bin/env python3
"""DEV-ONLY (TECH v0.7.1): generate patches/item_v071_hooks.py from devtools/hooks_v071_spec.py and the exact
Rev 1 instruction index (devtools/rev1_insn_index.py). The expected original bytes are taken from the index
(i.e. from the clean ROM) and written literally into the generated file, so the builder never needs the
disassembly; the builder re-asserts every byte against the clean ROM at build time.

usage: gen_hooks_v071.py <insn.tsv> <out.py>
spec entry: (id, "C3:8696", n_insns, "asm text", consumer, reason[, extra])
"""
import os, sys, pprint
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from hooks_v071_spec import SPEC


def main(tsv, out):
    rows = {}
    order = []
    for l in open(tsv):
        f = l.rstrip("\n").split("\t")
        rows[f[0]] = f
        order.append(f[0])
    idx = {a: i for i, a in enumerate(order)}
    hooks = []
    seen = set()
    for e in SPEC:
        hid, site, n, asm, consumer, reason = e[:6]
        extra = e[6] if len(e) > 6 else {}
        if isinstance(n, str):              # data site: literal expected bytes (asserted by the builder)
            h = {"id": hid, "snes": site.replace(":", ""), "expect": n, "asm": asm, "consumer": consumer,
                 "reason": reason, "original_asm": "(data)"}
            h.update(extra)
            hooks.append(h)
            continue
        if site not in rows:
            raise SystemExit(f"{hid}: {site} is not an instruction start")
        i = idx[site]
        ins = [rows[order[i + k]] for k in range(n)]
        b = bytes.fromhex(" ".join(r[1] for r in ins))
        # contiguity check
        a = int(site.replace(":", ""), 16)
        for r in ins:
            if int(r[0].replace(":", ""), 16) != a:
                raise SystemExit(f"{hid}: instructions not contiguous at {r[0]}")
            a += len(bytes.fromhex(r[1]))
        if site in seen:
            raise SystemExit(f"duplicate site {site}")
        seen.add(site)
        h = {"id": hid, "snes": site.replace(":", ""), "expect": b.hex(" ").upper(), "asm": asm,
             "consumer": consumer, "reason": reason,
             "original_asm": " / ".join(r[6].split(";")[0].strip() for r in ins)}
        h.update(extra)
        hooks.append(h)
    with open(out, "w") as f:
        f.write('"""GENERATED by devtools/gen_hooks_v071.py from devtools/hooks_v071_spec.py + the Rev 1 instruction index.\n'
                'Do not edit by hand. Every vanilla byte the TECH v0.7.1 engine changes outside the relocated-table operand\n'
                'retargets: id, SNES site, exact Rev 1 bytes (re-asserted against the clean ROM by the builder), the\n'
                'replacement as assembler text (assembled at the site, same length), the consumer and the reason."""\n\n')
        f.write("HOOKS = " + pprint.pformat(hooks, width=118, sort_dicts=False) + "\n")
    print(len(hooks), "hooks ->", out)


if __name__ == "__main__":
    main(*sys.argv[1:3])
