"""TECH v0.7.1 hook specification (input of devtools/gen_hooks_v071.py).
(id, site, number of original instructions replaced | literal data bytes, replacement asm, consumer, reason[, extra])"""

INV_B = "16-bit id (B = high bit) for the following extended-aware lookup"
MASK = "extended slot reads as $FF: never selectable / never matched by a vanilla id"

SPEC = [
    # ======================================================================= C0 field / events
    ("I201_EVCMD_66", "C0:9926", "1A B9", ".word XC0_Ev66 & $FFFF",
     "EventCmdTbl entry $66 (vanilla EventCmd_66 = RTS lock-up; unused by Rev 1 scripts)", "GIVE_EXT_ITEM id16 (3 bytes)"),
    ("I202_EVCMD_67", "C0:9928", "1A B9", ".word XC0_Ev67 & $FFFF",
     "EventCmdTbl entry $67 (vanilla unused)", "TAKE_EXT_ITEM id16 (3 bytes)"),
    ("I203_EVCMD_68", "C0:992A", "1A B9", ".word XC0_Ev68 & $FFFF",
     "EventCmdTbl entry $68 (vanilla unused)", "HAS_EXT_ITEM id16, switch16 (5 bytes)"),
    ("I210_GIVEITEM_FIND", "C0:ACFE", 1, "jsr XC0_LdaInvXMask",
     "GiveItem C0:ACFC (event $80, treasure chests) find-same-item loop", MASK),
    ("I211_GIVEITEM_PUT", "C0:AD19", 1, "jsr XC0_StaInvXClr",
     "GiveItem first-empty-slot store", "vanilla id stored -> slot high bit cleared"),
    ("I212_TAKEITEM_FIND", "C0:AD2F", 1, "jsr XC0_LdaInvXMask", "EventCmd_81 take-item search", MASK),
    ("I213_EVCMD8D_SLOT", "C0:9FE7", 1, "jsr XC0_8dLoad", "EventCmd_8d (remove character equipment) slot read",
     "extended equipment returns to the inventory with its 9-bit id; vanilla path sees $FF and skips it"),
    ("I214_EVCMD8D_FIND", "C0:9FF7", 1, "jsr XC0_LdaInvXMask", "EventCmd_8d find-same-item loop", MASK),
    ("I215_EVCMD8D_PUT", "C0:A017", 1, "jsr XC0_StaInvXClr", "EventCmd_8d empty-slot store",
     "vanilla id stored -> slot high bit cleared"),
    ("I216_CHARINIT_EQUIP", "C0:A0D0", 1, "jsr XC0_InitEqp",
     "character init from CharProp (6 equipment bytes := vanilla ids)", "clear the record's 6 equipment high bits"),
    ("I220_NEWGAME_EXT", "C0:BDE2", 2, "jsl XJ_NewGame\nbra $C0BDF1",
     "InitNewGame Bushido-name copy to $1CF8-$1D27 (JP leftover, never read by the EN game)",
     "extended metadata := 0 + signature; the copy loop is bypassed"),
    # ======================================================================= C3 save / load
    ("I221_LOADGAME_SANITIZE", "C3:150E", 1, "jsr XC3_LoadOK",
     "LoadSavedGame (game-over restart) after the slot checksum passed",
     "no/legacy signature -> clear extended metadata; valid -> drop stale/undefined bits; then PopTimers"),
    ("I222_LOADMENU_SANITIZE", "C3:29EB", 1, "jsr XC3_LoadSlotSan", "load menu slot select (title Continue)",
     "same sanitize right after LoadSaveSlot"),
    # ======================================================================= C3 item menu
    ("I300_ITEMLIST_QTY", "C3:7FA8", 1, "jsr XC3_LdaQtyList", "DrawItemListRow quantity",
     "shop / colosseum: extended slot drawn as empty (qty 0)"),
    ("I301_ITEMLIST_NAME", "C3:80C7", 2, "jsr XC3_ListNameY\nrts",
     "LoadListItemName (item menu, shop sell list, colosseum list)",
     "name via XItemName with the 9-bit id; shop/colosseum: extended slot drawn as empty", {"pad_nop": True}),
    ("I302_ITEMDESC_ID", "C3:82F8", 1, "jsr XC3_LdaInvY", "InitItemDesc item id", INV_B),
    ("I303_ITEMDESC_LOAD", "C3:82FB", 1, "jsr XC3_ItemDescB", "InitItemDesc LoadItemDesc",
     "extended description from XDescPtr/XDescText (hidden in shop/colosseum)"),
    ("I304_USEITEM_ID", "C3:849D", 1, "jsr XC3_LdaInvY", "UseItem item id", INV_B),
    ("I305_USEITEM_PROP", "C3:84A8", 1, "jsr XC3_PropPtrB", "UseItem GetItemPropPtr",
     "type / equippable characters of the extended item (item details screen)"),
    ("I306_DETAILS_ID", "C3:8696", 1, "jsr XC3_LdaInvY", "DrawItemDetails item id", INV_B),
    ("I307_DETAILS_PROP", "C3:8699", 1, "jsr XC3_PropPtrB", "DrawItemDetails GetItemPropPtr",
     "stats / elements / power of the extended item"),
    ("I308_DETAILS_POWER", "C3:87A0", 1, "jsr XC3_LdaInvYMask", "DrawWeaponPower Atma/Soul Sabre/Dice id test",
     "an extended weapon is never one of the vanilla '???' weapons (low byte alias)"),
    ("I309_ITEM_SWAP_BITS", "C3:27DE", 1, "jmp XC3_SwapBits", "item move: swap two inventory slots",
     "swap the two slots' high bits too"),
    ("I310_ARRANGE", "C3:267F", 2, "jsl XJ_Arrange\nnop\nnop", "Arrange (copy + SortItemsByIcon)",
     "same algorithm/buffers, 9-bit ids carried, icon from XItemName"),
    ("I311_COLOSSEUM_PICK", "C3:ACFA", 1, "jsr XC3_LdaInvXMask", "colosseum item select (wager)",
     "extended items cannot be wagered"),
    # ======================================================================= C3 equip / relic
    ("I320_PARTYEQ_NAME_ID", "C3:8FC2", 1, "jsr XC3_LdaEq1F", "DrawPartyEquipItems equipment id", INV_B),
    ("I321_EQNAME", "C3:8FE1", 2, "jmp XC3_EqpName\nnop", "_c38fe1 equipped item name",
     "name via XItemName with the 9-bit id", {"pad_nop": True}),
    ("I322_EQNAME_RH", "C3:9405", 1, "jsr XC3_LdaEq1F", "equip menu R-hand name", INV_B),
    ("I323_EQNAME_LH", "C3:9417", 1, "jsr XC3_LdaEq20", "equip menu L-hand name", INV_B),
    ("I324_EQNAME_HEAD", "C3:943D", 1, "jsr XC3_LdaEq21", "equip menu helmet name", INV_B),
    ("I325_EQNAME_BODY", "C3:944B", 1, "jsr XC3_LdaEq22", "equip menu armor name", INV_B),
    ("I326_EQNAME_RELIC1", "C3:9459", 1, "jsr XC3_LdaEq23", "relic menu relic 1 name", INV_B),
    ("I327_EQNAME_RELIC2", "C3:9467", 1, "jsr XC3_LdaEq24", "relic menu relic 2 name", INV_B),
    ("I330_PREVIEW_SAVE", "C3:925F", 2, "jsr XC3_PrevSave\nnop\nnop", "_c39233 stat preview: save equipped item",
     "save the slot's high bit too (XSCRATCH $1E3F, transient)"),
    ("I331_PREVIEW_CAND", "C3:9264", 1, "jsr XC3_LdaInvX", "_c39233 candidate id", INV_B),
    ("I332_PREVIEW_PUT", "C3:9267", 1, "jsr XC3_StaEq1F", "_c39233 temporary equip of the candidate",
     "equipment high bit := candidate high bit for UpdateEquip"),
    ("I333_PREVIEW_RESTORE", "C3:931A", 2, "jsr XC3_PrevRestore\nnop\nnop", "_c39233 restore equipped item",
     "restore the slot's id and high bit"),
    ("I340_REMOVEALL", "C3:96A8", 1, "jmp XC3_RemoveAll", "EquipRemoveAll (Empty, Optimum)",
     "weapon/shield/helmet/armor return to the inventory with their 9-bit ids; high bits cleared"),
    ("I341_OPT_2H_STORE", "C3:9712", 1, "jsr XC3_StaEq1F", "EquipOptimum 2-handed weapon store", "high bit := B"),
    ("I342_OPT_2H_DEC", "C3:9715", 1, "jsr XC3_DecQtyB", "EquipOptimum DecItemQty", "9-bit id removal"),
    ("I343_OPT_W_STORE", "C3:972A", 1, "jsr XC3_StaEq1F", "EquipOptimum weapon store", "high bit := B"),
    ("I344_OPT_W_DEC", "C3:972D", 1, "jsr XC3_DecQtyB", "EquipOptimum DecItemQty", "9-bit id removal"),
    ("I345_OPT_S_STORE", "C3:9749", 1, "jsr XC3_StaEq20", "EquipOptimum shield store", "high bit := B"),
    ("I346_OPT_S_DEC", "C3:974C", 1, "jsr XC3_DecQtyB", "EquipOptimum DecItemQty", "9-bit id removal"),
    ("I347_OPT_G_STORE", "C3:9763", 1, "jsr XC3_StaEq20", "EquipOptimum genji off-hand store", "high bit := B"),
    ("I348_OPT_G_DEC", "C3:9766", 1, "jsr XC3_DecQtyB", "EquipOptimum DecItemQty", "9-bit id removal"),
    ("I349_OPT_H_STORE", "C3:977A", 1, "jsr XC3_StaEq21", "EquipOptimum helmet store", "high bit := B"),
    ("I350_OPT_H_DEC", "C3:977D", 1, "jsr XC3_DecQtyB", "EquipOptimum DecItemQty", "9-bit id removal"),
    ("I351_OPT_A_STORE", "C3:978F", 1, "jsr XC3_StaEq22", "EquipOptimum armor store", "high bit := B"),
    ("I352_OPT_A_DEC", "C3:9792", 1, "jmp XC3_DecQtyB", "EquipOptimum DecItemQty (tail)", "9-bit id removal"),
    ("I353_VALIDW_ID", "C3:979F", 1, "jsr XC3_LdaInvY", "GetValidWeapons item id", INV_B),
    ("I354_VALIDW_PROP", "C3:97A6", 1, "jsr XC3_PropPtrB", "GetValidWeapons type/equippable", "extended properties"),
    ("I355_VALIDS_ID", "C3:97E1", 1, "jsr XC3_LdaInvY", "GetValidShields item id", INV_B),
    ("I356_VALIDS_PROP", "C3:97E8", 1, "jsr XC3_PropPtrB", "GetValidShields type/equippable", "extended properties"),
    ("I357_BESTEQUIP", "C3:9819", 3, "jmp XC3_GetBestEquip", "GetBestEquip (Optimum)",
     "returns the 9-bit id; extended items are never imp items (ImpItem low-byte aliases $12/$16/$1C/$24)",
     {"pad_nop": True}),
    ("I358_BEST2HAND", "C3:983F", 1, "jmp XC3_GetBest2Hand\nnop", "GetBest2Hand (Optimum, gauntlet)",
     "returns the 9-bit id; 2-hand flag from the extended properties", {"pad_nop": True}),
    ("I359_REMOVE_ID", "C3:98E6", 1, "jsr XC3_LdaEq1F", "equip Remove (one slot) id", INV_B),
    ("I360_REMOVE_INC", "C3:98E9", 1, "jsr XC3_IncQtyB", "equip Remove IncItemQty", "9-bit id back to inventory"),
    ("I361_REMOVE_CLR", "C3:98EE", 1, "jsr XC3_StaEq1F", "equip Remove slot := $FF", "high bit cleared"),
    ("I362_EQUIP_OLD", "C3:9923", 1, "jsr XC3_LdaEq1F", "equip (item select) currently equipped id", INV_B),
    ("I363_EQUIP_INC", "C3:992A", 1, "jsr XC3_IncQtyB", "equip IncItemQty (old item back)", "9-bit id"),
    ("I364_EQUIP_NEW", "C3:9936", 1, "jsr XC3_LdaInvX", "equip new item id", INV_B),
    ("I365_EQUIP_STORE", "C3:9939", 1, "jsr XC3_StaEq1F", "equip store", "high bit := B"),
    ("I366_EQUIP_DEC", "C3:993C", 1, "jsr XC3_DecQtyB", "equip DecItemQty (new item out)", "9-bit id"),
    ("I367_HANDTXT_LH", "C3:99A6", 1, "jsr XC3_LdaEq20", "R-Hand/L-Hand text (gauntlet) L-hand id", INV_B),
    ("I368_HANDTXT_LH_P", "C3:99AF", 1, "jsr XC3_PropPtrB", "R-Hand/L-Hand text 2-hand flag", "extended properties"),
    ("I369_HANDTXT_RH", "C3:99CA", 1, "jsr XC3_LdaEq1F", "R-Hand/L-Hand text R-hand id", INV_B),
    ("I370_HANDTXT_RH_P", "C3:99CD", 1, "jsr XC3_PropPtrB", "R-Hand/L-Hand text 2-hand flag", "extended properties"),
    ("I371_HANDFX_LH", "C3:9A0E", 1, "jsr XC3_LdaEq20", "CheckHandEffects L-hand id", INV_B),
    ("I372_HANDFX_LH_P", "C3:9A17", 1, "jsr XC3_PropPtrB", "CheckHandEffects 2-hand flag", "extended properties"),
    ("I373_HANDFX_RH", "C3:9A2B", 1, "jsr XC3_LdaEq1F", "CheckHandEffects R-hand id", INV_B),
    ("I374_HANDFX_RH_P", "C3:9A2E", 1, "jsr XC3_PropPtrB", "CheckHandEffects 2-hand flag", "extended properties"),
    ("I375_CANEQ_ID", "C3:9A5D", 1, "jsr XC3_LdaInvX", "CheckCanEquipItem candidate id", INV_B),
    ("I376_CANEQ_PROP", "C3:9A60", 1, "jsr XC3_PropPtrB", "CheckCanEquipItem candidate type", "extended properties"),
    ("I377_CANEQ_LH", "C3:9A79", 1, "jsr XC3_LdaEq20", "CheckCanEquipItem L-hand id", INV_B),
    ("I378_CANEQ_LH_P", "C3:9A80", 1, "jsr XC3_PropPtrB", "CheckCanEquipItem L-hand type", "extended properties"),
    ("I379_CANEQ_RH", "C3:9AA5", 1, "jsr XC3_LdaEq1E", "CheckCanEquipItem R-hand id ($001E,Y)", INV_B),
    ("I380_CANEQ_RH_P", "C3:9AAC", 1, "jsr XC3_PropPtrB", "CheckCanEquipItem R-hand type", "extended properties"),
    ("I381_VALIDE_ID", "C3:9B76", 1, "jsr XC3_LdaInvY", "GetValidEquip weapon/shield id", INV_B),
    ("I382_VALIDE_PROP", "C3:9B7D", 1, "jsr XC3_PropPtrB", "GetValidEquip weapon/shield type", "extended properties"),
    ("I383_VALIDH_ID", "C3:9BB6", 1, "jsr XC3_LdaInvY", "GetValidEquip helmet id", INV_B),
    ("I384_VALIDH_PROP", "C3:9BBD", 1, "jsr XC3_PropPtrB", "GetValidEquip helmet type", "extended properties"),
    ("I385_VALIDA_ID", "C3:9BF2", 1, "jsr XC3_LdaInvY", "GetValidEquip armor id", INV_B),
    ("I386_VALIDA_PROP", "C3:9BF9", 1, "jsr XC3_PropPtrB", "GetValidEquip armor type", "extended properties"),
    ("I387_EQLIST_NAME_ID", "C3:9D25", 1, "jsr XC3_LdaInvY", "LoadEquipListItemName id", INV_B),
    ("I388_EQLIST_NAME_HI", "C3:9D2F", 1, "jsr XC3_HiM7A", "LoadEquipListItemName M7A high byte",
     "name index = 9-bit id * 13 (ItemName retargeted to XItemName)"),
    ("I389_INCQTY_FIND", "C3:9D63", 1, "jsr XC3_CmpInvYMask", "IncItemQty find-same-item", MASK),
    ("I390_INCQTY_PUT", "C3:9D85", 1, "jsr XC3_StaInvYClr", "IncItemQty empty-slot store",
     "vanilla id stored -> high bit cleared"),
    ("I391_DECQTY_FIND", "C3:9D9C", 1, "jsr XC3_CmpInvYMask", "DecItemQty find item", MASK),
    ("I392_VALIDR_ID", "C3:A05F", 1, "jsr XC3_LdaInvY", "relic list builder id", INV_B),
    ("I393_VALIDR_PROP", "C3:A066", 1, "jsr XC3_PropPtrB", "relic list builder type/equippable", "extended properties"),
    ("I394_RELIC_OLD", "C3:A0BB", 1, "jsr XC3_LdaEq23", "relic equip currently equipped id ($0023,Y)", INV_B),
    ("I395_RELIC_INC", "C3:A0C2", 1, "jsr XC3_IncQtyB", "relic equip IncItemQty", "9-bit id"),
    ("I396_RELIC_NEW", "C3:A0CE", 1, "jsr XC3_LdaInvX", "relic equip new id", INV_B),
    ("I397_RELIC_STORE", "C3:A0D1", 1, "jsr XC3_StaEq23", "relic equip store", "high bit := B"),
    ("I398_RELIC_DEC", "C3:A0D4", 1, "jsr XC3_DecQtyB", "relic equip DecItemQty", "9-bit id"),
    ("I399_RELICRM_ID", "C3:A124", 1, "jsr XC3_LdaEq23", "relic remove id", INV_B),
    ("I400_RELICRM_INC", "C3:A127", 1, "jsr XC3_IncQtyB", "relic remove IncItemQty", "9-bit id"),
    ("I401_RELICRM_CLR", "C3:A12C", 1, "jsr XC3_StaEq23", "relic remove slot := $FF", "high bit cleared"),
    ("I402_SORT_ID", "C3:A16D", 1, "jsr XC3_LdaInvY", "SortValidEquip id", INV_B),
    ("I403_SORT_PROP", "C3:A170", 1, "jsr XC3_PropPtrB", "SortValidEquip attack/defense power", "extended properties"),
    ("I404_RELICDESC_1", "C3:A1CD", 1, "jsr XC3_LdaEq23", "relic slot description (relic 1)", INV_B),
    ("I405_RELICDESC_2", "C3:A1D2", 1, "jsr XC3_LdaEq24", "relic slot description (relic 2)", INV_B),
    ("I406_RELICDESC_LD", "C3:A1D5", 1, "jmp XC3_ItemDescB", "relic slot LoadItemDesc", "extended description"),
    ("I407_RELICLDESC_ID", "C3:A1E4", 1, "jsr XC3_LdaInvX", "relic list description id", INV_B),
    ("I408_RELICLDESC_LD", "C3:A1E7", 1, "jmp XC3_ItemDescB", "relic list LoadItemDesc", "extended description"),
    # ======================================================================= C3 shop
    ("I420_SELLDESC", "C3:B4FF", 1, "jsr XC3_LdaInvXMask", "shop sell description id", MASK),
    ("I421_SELLITEM", "C3:BFCF", 1, "jsr XC3_LdaInvYMask", "_c3bfcb shop selected inventory item (sell select/qty/price)",
     "extended items cannot be sold"),
    ("I422_BUY_FIND", "C3:B5BC", 1, "jsr XC3_CmpInvYMask", "shop buy: find same item", MASK),
    ("I423_BUY_PUT", "C3:B5DC", 1, "jsr XC3_StaInvYClr", "shop buy: new slot store", "high bit cleared"),
    ("I424_OWNED_FIND", "C3:BC66", 1, "jsr XC3_CmpInvYMask", "shop owned-quantity search", MASK),
    ("I425_EQUIPPED_CNT", "C3:BF97", 2, "jsr XC3_ShopEqCmp\nnop", "shop equipped-count compare",
     "an extended equipment byte never equals a shop (vanilla) item"),
    ("I430_CMP_ARMOR_ID", "C3:BD5B", 1, "jsr XC3_LdaEq22", "shop party compare: armor id", INV_B),
    ("I431_CMP_ARMOR_P", "C3:BD66", 1, "jsr XC3_PropPtrB", "shop party compare: armor defense", "extended power"),
    ("I432_CMP_W_EQ1", "C3:BDBA", 1, "jsr XC3_LdaEqM1F", "shop party compare: weapon == shop item (R)", MASK),
    ("I433_CMP_W_EQ2", "C3:BDC1", 1, "jsr XC3_LdaEqM20", "shop party compare: weapon == shop item (L)", MASK),
    ("I434_CMP_W_R", "C3:BDC9", 1, "jsr XC3_LdaEq1F", "shop party compare: R-hand id", INV_B),
    ("I435_CMP_W_R_P", "C3:BDD0", 1, "jsr XC3_PropPtrB", "shop party compare: R-hand type", "extended properties"),
    ("I436_CMP_W_L", "C3:BDE1", 1, "jsr XC3_LdaEq20", "shop party compare: L-hand id", INV_B),
    ("I437_CMP_W_L_P", "C3:BDE8", 1, "jsr XC3_PropPtrB", "shop party compare: L-hand type", "extended properties"),
    ("I438_CMP_W_L2", "C3:BDF9", 1, "jsr XC3_LdaEq20", "shop party compare: L-hand id (power)", INV_B),
    ("I439_CMP_W_R2", "C3:BDFF", 1, "jsr XC3_LdaEq1F", "shop party compare: R-hand id (power)", INV_B),
    ("I440_CMP_W_POW", "C3:BE06", 1, "jsr XC3_PropPtrB", "shop party compare: weapon power", "extended power"),
    ("I441_CMP_S_EQ1", "C3:BE4A", 1, "jsr XC3_LdaEqM1F", "shop party compare: shield == shop item (R)", MASK),
    ("I442_CMP_S_EQ2", "C3:BE51", 1, "jsr XC3_LdaEqM20", "shop party compare: shield == shop item (L)", MASK),
    ("I443_CMP_S_L", "C3:BE59", 1, "jsr XC3_LdaEq20", "shop party compare: L-hand id", INV_B),
    ("I444_CMP_S_L_P", "C3:BE5C", 1, "jsr XC3_PropPtrB", "shop party compare: L-hand type", "extended properties"),
    ("I445_CMP_S_R", "C3:BE6D", 1, "jsr XC3_LdaEq1F", "shop party compare: R-hand id", INV_B),
    ("I446_CMP_S_R_P", "C3:BE70", 1, "jsr XC3_PropPtrB", "shop party compare: R-hand type", "extended properties"),
    ("I447_CMP_S_R2", "C3:BE81", 1, "jsr XC3_LdaEq1F", "shop party compare: R-hand id (power)", INV_B),
    ("I448_CMP_S_L2", "C3:BE87", 1, "jsr XC3_LdaEq20", "shop party compare: L-hand id (power)", INV_B),
    ("I449_CMP_S_POW", "C3:BE8E", 1, "jsr XC3_PropPtrB", "shop party compare: shield power", "extended power"),
    ("I450_CMP_H_ID", "C3:BED3", 1, "jsr XC3_LdaEq21", "shop party compare: helmet id", INV_B),
    ("I451_CMP_H_P", "C3:BEDE", 1, "jsr XC3_PropPtrB", "shop party compare: helmet power", "extended power"),

    # ======================================================================= C2 shared UpdateEquip
    ("I500_UPDEQ_LOAD", "C2:0EE6", 1, "jsr XC2_EqLoad", "UpdateEquip 6-slot loop equipment read ($15FB,X)",
     "low byte + equipment high bit (B) for CalcEquipEffect: all stats/elements/effects of extended equipment"),
    ("I501_CALCEQ_OFS", "C2:0F9C", 4, "jsr XC2_PropOfs", "CalcEquipEffect id*30 (XBA/LDA #$1E/JSR MultAB/TAX)",
     "16-bit ItemProp offset of the 9-bit id (ItemProp retargeted to XItemProp)", {"pad_nop": True}),
    ("I502_LEARN_OFS", "C2:600C", 3, "jsr XC2_LearnOfs", "LearnItemMagic id*30 (battle end, equipped items)",
     "spell-learning bytes of extended equipment from XItemProp", {"pad_nop": True}),
    # ======================================================================= C2 battle inventory
    ("I510_BINV_HAND_L", "C2:5481", 1, "jsr XC2_HandL", "InitInventory L-hand (shield slot) read",
     "9-bit id of the hand item (also clears the battle name queue)"),
    ("I511_BINV_HAND_L_CP", "C2:5485", 1, "jsr XC2_CopyItemPropB", "InitInventory L-hand CopyItemProp",
     "extended hand item: properties from XItemProp, never usable/throwable"),
    ("I512_BINV_HAND_R", "C2:5493", 1, "jsr XC2_HandR", "InitInventory R-hand (weapon slot) read", "9-bit id"),
    ("I513_BINV_HAND_R_CP", "C2:5497", 1, "jsr XC2_CopyItemPropB", "InitInventory R-hand CopyItemProp",
     "extended hand item: properties from XItemProp, never usable/throwable"),
    ("I516_BINV_EXT_EMPTY", "C2:54B0", 2, "jsr XC2_ExtSlotsEmpty", "InitInventory: end of the 256-slot copy loop (SEP #$30 / TDC)",
     "every extended slot is re-copied as the vanilla loop copies an empty slot (qty 0, CopyItemProp($FF)): not in "
     "Item/Throw/Tools lists, cannot be used or truncated; zero bitmap bytes skipped (battle init timing unchanged)",
     {"mode": ".a16\n.i16"}),
    ("I520_BTLEND_INV", "C2:4981", 2, "jsl XJ_BattleEndInv\nbra $C2499E", "battle end: battle inventory -> $1869/$1969",
     "vanilla slots copied as before; extended slots preserved; vanilla items placed at their positions re-homed"),
    ("I521_BTLEND_WAGER", "C2:49AD", 1, "jsr XC2_CmpInvXMask", "battle end: colosseum wager removal search", MASK),
    ("I530_ANIM_ID", "C2:29FE", 1, "jsr XC2_AnimId", "weapon animation number (RHandItem+1 -> $B7)",
     "extended weapon -> animation number $C0+low byte (XWeaponAnimFull)", {"mode": ".a8\n.i8"}),
    ("I531_SPEAR_R", "C2:1814", 2, "jsr XC2_SpearR", "Jump: SpearEffect(RHandItem)",
     "extended spear (XExtFlags bit1) doubles Jump damage like vanilla $1D-$24", {"pad_nop": True}),
    ("I532_SPEAR_L", "C2:181A", 2, "jsr XC2_SpearL", "Jump: SpearEffect(LHandItem)", "as above, left hand",
     {"pad_nop": True}),
    ("I533_OGRE_NIX", "C2:3F0B", 1, "jsr XC2_OgreLoad", "MP-crit weapon break test (Ogre Nix id $17)",
     "an extended weapon never matches (would be broken/lost)"),
    # ======================================================================= C1 battle menu (JSL to bank FA)
    ("I540_HANDNAMES", "C1:4BDA", 2, "jsl XJ_HandNames", "battle Item menu hand header (L-hand id store)",
     "name queue for extended hand items", {"pad_nop": True}),
    ("I541_NAMEIDX", "C1:656C", 2, "jsl XJ_NameIdx", "ListTextCmd_0e name index (LDX $30 / LDA $56)",
     "extended hand name from XItemName"),
    ("I542_SWAPGUARD", "C1:89D2", 2, "jsl XJ_SwapGuard", "check_equip (battle hand <-> inventory exchange, 3 callers)",
     "the replaced hand (identified by the caller) cannot hold an extended item: refused like a vanilla refusal",
     {"pad_nop": True}),
    ("I545_HANDSWAP_BITS", "C1:8E8F", 2, "jsl XJ_HandSwapBits", "SelectEquipItem R-hand <-> L-hand exchange (LDX w7e7b05 / TDC)",
     "the two hand equipment bits are swapped with the hand entries (write-back C2:20AB stores low bytes)"),
    ("I543_JUMPANIM_L", "C1:BA41", 2, "jsl XJ_JumpAnimL", "Jump animation: L-hand item id + 1 (ItemJumpThrowAnim index)",
     "extended weapon -> $80 + low byte (XJumpAnim FA:3700; the C1:BA4C operand is retargeted)"),
    ("I544_JUMPANIM_R", "C1:BA47", 2, "jsl XJ_JumpAnimR", "Jump animation: R-hand item id + 1 (ItemJumpThrowAnim index)",
     "as I543 (right hand)"),
]
