#!/usr/bin/env python3
"""DEV-ONLY (TECH v0.7.1): list every Rev 1 long-operand consumer of ItemProp (D8:5000, 256x30) and
ItemName (D2:B300, 256x13) from the exact Rev 1 instruction index (devtools/rev1_insn_index.py) and write
data/item_relocation_v071.json (consumed by patches/item_v071.py, which re-asserts every byte against the
clean ROM). usage: item_relocation_v071.py <insn.tsv> <out.json>"""
import json, sys

TABLES = {"ITEM_PROP": (0xD85000, 0xD86DFF, 0xFA0000), "ITEM_NAME": (0xD2B300, 0xD2BFFF, 0xFA2580),
          "WEAPON_ANIM": (0xECE400, 0xECE6E7, 0xFA3800), "JUMP_ANIM": (0xD10040, 0xD10140, 0xFA3700)}
# ItemJumpThrowAnim (D1:0040, 1 + 256 entries, index = item + 1) has two consumers: the Jump animation (C1:BA4C,
# index from the hand item, hooked I543/I544 -> extended weapon = $C0 + low byte) and the Throw animation
# (C1:B9CC, index from the thrown item; extended items can never be thrown, so it keeps the vanilla table).
ONLY = {"JUMP_ANIM": {"C1:BA4C"}}
EXCLUDED = {"JUMP_ANIM": {"C1:B9CC": "Throw: thrown item ids are vanilla only (extended items are never throwable)"}}


def main(tsv, out):
    rows = [l.rstrip("\n").split("\t") for l in open(tsv)]
    res = {"_comment": "Generated by devtools/item_relocation_v071.py from the Rev 1 instruction index "
                       "(everything8215/ff6 ROM_VERSION=1, byte-identical to the clean ROM). Every long-indexed "
                       "operand that addresses the vanilla table is retargeted to the 320-entry copy.",
           "tables": {}}
    for name, (a, b, nb) in TABLES.items():
        cons = []
        for f in rows:
            if f[3] not in ("absl", "abslx"):
                continue
            v = int(f[4], 16)
            if a <= v <= b:
                if name in ONLY and f[0] not in ONLY[name]:
                    if f[0] not in EXCLUDED.get(name, {}):
                        raise SystemExit(f"{name}: unreviewed consumer {f[0]}")
                    continue
                cons.append({"snes": f[0].replace(":", ""), "bytes": f[1], "kind": "long", "disp": v - a,
                             "src": f"{f[5]} {f[6].strip()[:60]}"})
        res["tables"][name] = {"old_base": f"{a:06X}", "old_end": f"{b:06X}", "new_base": f"{nb:06X}",
                               "consumers": cons}
        if name in EXCLUDED:
            res["tables"][name]["excluded_consumers"] = EXCLUDED[name]
        print(name, len(cons), "consumers")
    json.dump(res, open(out, "w"), indent=1)


if __name__ == "__main__":
    main(*sys.argv[1:3])
