#!/usr/bin/env python3
"""Regenerate data/vram_safety.json from the measured Magitek conflict mask (TECH v0.6.2 R13 audit).
Evidence: out/magitek_vram_v062/ (VRAM diff Magitek vs no Magitek, 1/2/3 riders, formations $002/$004/$008),
out/magitek_screen_v062*/ (12 vanilla formations on screen, Magitek vs no Magitek)."""
import json, os, sys
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
from ff6x.formation_safety import build_vram_safety_table

MASK = sorted((r, c) for r in range(12) for c in range(12, 16))
doc = {
    "_comment": "TECH v0.6.2 machine-readable VRAM safety table. Generated by devtools/make_vram_safety.py; selftest 52 "
                "recomputes it. Cell (row, col) = 8x8 tile in the 16x16-cell monster graphics area (btlgfx buffer 7E:AE3F, "
                "uploaded linearly to VRAM $6000 + 32 * (row * 16 + col)).",
    "monster_vram": {"vram_byte_start": "6000", "vram_byte_end": "7FFF", "cell_bytes": 32, "grid": [16, 16],
                     "source": "MonsterVRAMMapPtrs C2:D01A (formation byte 0 >> 4) -> ff6x/enemygfx.py VRAM_MAPS / VRAM_MAP_POS"},
    "magitek": {
        "condition": "any party member with Magitek status (character record $1614 + 37*k bit 3)",
        "conflict_cells_row_col": [list(x) for x in MASK],
        "conflict_area": "rows 0-11, columns 12-15 (48 cells; VRAM $6180-$61FF, $6380-$63FF, ... per row)",
        "independent_of": ["number of riders (1, 2, 3 measured)", "formation / VRAM map ($002 map 8, $004 map 12, $008 map 1)",
                           "MagiTek beam command animations (no sprite cell of a safe layout overwritten while monsters alive: $001, $002, $011, $071, $03C)"],
        "first_overwrite_frame": "about 90-120 frames after the formation is loaded (before the monsters are visible)",
        "evidence": ["out/magitek_vram_v062/*.json", "out/magitek_screen_v062/", "out/magitek_screen_v062n/"],
    },
    "normal_party": {"conflict_cells_row_col": [], "note": "no conflict observed (12 formations exact on screen without Magitek); other special party graphics not audited"},
    "vram_maps": build_vram_safety_table(set(MASK)),
}
open(os.path.join(HERE, "data", "vram_safety.json"), "w").write(json.dumps(doc, indent=1) + "\n")
print("written data/vram_safety.json")
