#!/usr/bin/env python3
"""Dev-only (needs the everything8215 ff6 disassembly built with ROM_VERSION=1).
Enumerates every code reference to the per-map tables via the ca65 debug info,
resolves absolute addresses, verifies the instruction bytes in the CLEAN Rev 1 ROM,
and writes:
  audits/map_consumers_v0.4.json   (evidence: address, bytes, source line)
  data/map_relocation_v04.json     (builder input: operand retargets; no GPL text)
usage: map_consumer_audit.py <ff6dis dir> <clean_rev1.sfc>"""
import sys, os, json
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "devtools"))
from dbgrefs import Dbg
dis, romp = sys.argv[1], sys.argv[2]
rom = open(romp, "rb").read()
D = Dbg(os.path.join(dis, "build/en/rom/ff6-en.dbg"))
# table: (old ptr base, old data base, old end incl., record size, old ptr count, ptr/data symbols)
TABLES = {
 "EVENT_TRIGGERS":  dict(ptr=0xC40000, data=0xC40000, end=0xC41A0F, rec=5, ptrs=417, segs=["event_triggers"]),
 "NPC_PROPS":       dict(ptr=0xC41A10, data=0xC41A10, end=0xC46ABF, rec=9, ptrs=417, segs=["npc_prop"]),
 "SHORT_ENTRANCES": dict(ptr=0xDFBB00, data=0xDFBB00, end=0xDFD9FF, rec=6, ptrs=513, segs=["short_entrance"]),
 "LONG_ENTRANCES":  dict(ptr=0xEDF480, data=0xEDF480, end=0xEDFDFF, rec=7, ptrs=513, segs=["long_entrance"]),
 "TREASURE":        dict(ptr=0xED82F4, data=0xED8634, end=0xED8BC9, rec=5, ptrs=416, segs=["treasure_prop"]),
 "MAP_PROPS":       dict(ptr=None, data=0xED8F00, end=0xEDC47F, rec=33, rows=415, segs=["map_prop"]),
 "SUBTILEMAP_PTRS": dict(ptr=0xD9CD90, data=None, end=0xD9D1AF, rec=3, entries=352, segs=["sub_tilemap"]),
}
LONG = {0xAF, 0xBF, 0x8F, 0x9F, 0xCF, 0xDF, 0x2F, 0x3F, 0x0F, 0x1F, 0x4F, 0x5F, 0x6F, 0x7F, 0xEF, 0xFF}
names = set()
for t in TABLES.values():
    for sg in t["segs"]:
        for s in D.seg_syms(sg):
            if s["name"][:1].isupper() and not s["name"].startswith("LOCAL"):
                names.add(s["name"])
refs = {}
for nm in names:
    for s in D.syms_by_name[nm]:
        for r in s.get("ref", "").split("+"):
            if not r: continue
            lid = int(r); f, ln, txt = D.line_src(lid)
            if "/event/" in f or "sub_tilemap" in f or "map_prop" in f: continue
            for a, n in D.line_addrs(lid):
                refs[a] = (n, f, ln, txt)
out_audit, out_data = {}, {"_comment": "Generated by devtools/map_consumer_audit.py from the Rev 1 disassembly debug info; every entry is asserted against the clean ROM by the builder.", "tables": {}}
unclassified = []
for a in sorted(refs):
    n, f, ln, txt = refs[a]
    b = rom[a - 0xC00000:a - 0xC00000 + n]
    if not (n == 4 and b[0] in LONG):
        if "^" in txt or ".loword" in txt:
            unclassified.append({"snes": f"{a:06X}", "bytes": b.hex(" ").upper(), "src": f"{f}:{ln}", "text": txt})
        continue
    op = b[1] | b[2] << 8 | b[3] << 16
    for name, t in TABLES.items():
        lo = min(x for x in (t["ptr"], t["data"]) if x is not None)
        if lo <= op <= t["end"]:
            kind = "ptr" if (t["ptr"] is not None and (t["data"] is None or op < t["data"] or t["data"] == t["ptr"])) else "data"
            if t["data"] == t["ptr"]: kind = "ptr"
            base = t["ptr"] if kind == "ptr" else t["data"]
            e = {"snes": f"{a:06X}", "bytes": b.hex(" ").upper(), "operand": f"{op:06X}", "base": kind,
                 "disp": op - base}
            out_data["tables"].setdefault(name, {"consumers": []})["consumers"].append(e)
            out_audit.setdefault(name, []).append(dict(e, src=f"{f}:{ln}", text=txt))
            break
for name, t in TABLES.items():
    out_data["tables"].setdefault(name, {"consumers": []})
    out_data["tables"][name].update({k: (f"{v:06X}" if isinstance(v, int) and v > 0xFFFF else v) for k, v in t.items() if k != "segs"})
json.dump({"tables": out_audit, "immediate_refs_not_retargeted": unclassified,
           "counts": {k: len(v) for k, v in out_audit.items()}},
          open(os.path.join(HERE, "audits", "map_consumers_v0.4.json"), "w"), indent=1)
json.dump(out_data, open(os.path.join(HERE, "data", "map_relocation_v04.json"), "w"), indent=1)
print({k: len(v) for k, v in out_audit.items()}, "immediates:", len(unclassified))
