#!/usr/bin/env python3
"""Dev-only: write the machine-readable TECH v0.5 monster-ID dependency table
(audits/MONSTER_DEPENDENCY_TABLE_v0.5.json). Relocated tables + consumer patch points come from
data/monster_relocation_v05.json (generated by devtools/monster_consumer_audit.py from the ca65
.dbg of the disassembly and verified byte-by-byte against the clean Rev 1 ROM by the builder);
the non-relocated / engine entries below were audited by hand from the Rev 1 code paths listed."""
import json, os, sys
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); sys.path.insert(0, HERE)
from ff6x.allocations import Allocations
from patches import monster_v05 as MV

alloc = Allocations(os.path.join(HERE, "data", "allocations.json"))
R = MV.RELOC["tables"]
CONSUMER_NOTE = {
    "MONSTER_PROP": "LoadMonsterProp C2:2C30 (stats/HP/MP/exp/gil/level/elements/status/metamorph/special), LoadRageProp, Imp/Leap/Rage helpers",
    "MONSTER_ITEMS": "LoadMonsterProp (steal slots $3308/$3309), battle win drops",
    "MONSTER_OVERLAP": "btlgfx monster sprite priority (C1:2147)",
    "MONSTER_SPECIAL_ANIM": "LoadMonsterProp special-attack animation",
    "MONSTER_CONTROL": "Control command menu + controlled monster attack list",
    "MONSTER_SKETCH": "Sketch command attack choice",
    "MONSTER_NAME": "btlgfx target/monster name lists, battle messages, colosseum menu",
    "MONSTER_SPECIAL_NAME": "special attack name window",
    "AI_SCRIPT_PTRS": "InitMonsterAI C2:2D78",
    "AI_SCRIPT": "AI interpreter C2:1A44 / C2:1A64 / C2:1A6B, C2:2D88",
    "MONSTER_GFX_PROP": "monster sprite loader C1:2058-C1:20AB (via slot router), summon/Imp loaders C1:24FC-C1:2536 (vanilla slots), colosseum menu C3:AF5F-C3:AF77",
    "FORMATION_PROP": "LoadBattleProp C2:3136/C2:313D (aux 4 bytes -> $2F48-$2F4B)",
    "FORMATION_MONSTERS": "LoadBattleProp C2:3155, btlgfx formation init C1:0E99-C1:0EDF",
}


def relocated():
    out = []
    for name, t in R.items():
        reg = alloc.region(MV.TABLE_REGION[name], "production")
        new_base = 0xC00000 + reg["pc_start"]
        cons = []
        old = int(t["old_base"], 16)
        for c in t["consumers"]:
            ins = bytes.fromhex(c["bytes"])
            if c["kind"] == "long": new = (new_base + c["disp"]).to_bytes(3, "little")
            elif c["kind"] == "imm_bank": new = bytes([new_base >> 16])
            else: new = ((new_base & 0xFFFF) + c["disp"]).to_bytes(2, "little")
            cons.append({"instruction_snes": c["snes"], "instruction_pc": f"{int(c['snes'], 16) - 0xC00000:06X}",
                         "operand_snes": f"{int(c['snes'], 16) + 1:06X}", "kind": c["kind"], "disp": c["disp"],
                         "expected_instruction_bytes": c["bytes"],
                         "expected_operand_bytes": ins[1:1 + len(new)].hex(" ").upper(),
                         "new_operand_bytes": new.hex(" ").upper()})
        count = 1024 if name.startswith("FORMATION") else (MV.GFX_SLOTS if name == "MONSTER_GFX_PROP" else 512)
        out.append({
            "dependency": name, "class": "relocated",
            "vanilla_table": f"{t['old_base']}-{t['old_end']}", "record_size": t.get("record_size"),
            "vanilla_count": t.get("vanilla_count"),
            "nine_bit_ids_work_in_place": False,
            "reason": "only vanilla_count entries; IDs >= count would read the following table",
            "solution": f"relocated to {MV.TABLE_REGION[name]} {new_base:06X} ({count} entries), vanilla entries byte-identical, all consumers retargeted (operand bytes only)",
            "new_region": MV.TABLE_REGION[name], "new_base_snes": f"{new_base:06X}", "new_base_pc": f"{reg['pc_start']:06X}",
            "new_entries": count, "consumers_summary": CONSUMER_NOTE[name], "consumers": cons,
        })
    return out


MANUAL = [
    {"dependency": "FORMATION_RECORD_MSB", "class": "engine-native",
     "where": "formation byte 14 bits 0-5 (BattleMonsters); btlgfx C1:0ED1/C1:0EDF; battle InitMonsters C2:2EE1",
     "nine_bit_ids_work_in_place": True,
     "solution": "no change: monster ID = low byte (bytes 2-7) + msb bit; $1FF (low $FF + msb) = empty slot; builder writes empty slots as $1FF"},
    {"dependency": "BATTLE_RAM_MONSTER_IDS", "class": "engine-native",
     "where": "$2001+2*slot (btlgfx), $33A8+y / $2001-8+y (battle), 16-bit", "nine_bit_ids_work_in_place": True,
     "solution": "no change"},
    {"dependency": "MONSTER_GFX_SLOT_COLLISION", "class": "hooked",
     "where": "MonsterGfxProp D2:7000 slots $180-$19F = esper/summon + Imp graphics (GENJU_GFX, ldx #5*$19E)",
     "nine_bit_ids_work_in_place": False,
     "reason": "monster $180+ would load esper graphics properties",
     "solution": "slot(id) = id < $180 ? id : id + $20 via N300 router; hooks N301 C1:2058 (battle loader) and N302 C2:F5F1 (Sketch); summon/Imp paths unchanged",
     "patch_points": [
         {"snes": "C12058", "pc": "012058", "expected": "BD 01 20 0A 0A 18 7D 01 20", "new": "22 00 12 F0 EA EA EA EA EA"},
         {"snes": "C2F5F1", "pc": "02F5F1", "expected": "BD 01 20 AA", "new": "22 13 12 F0"}]},
    {"dependency": "COLOSSEUM_BATTLE_RANGE", "class": "hooked",
     "where": "InitParty C2:2F75: LDX wBattleID / CPX #$023E / BCC (vanilla: every battle >= $23E is colosseum)",
     "nine_bit_ids_work_in_place": False,
     "reason": "new formations $240-$3FF would be treated as colosseum (monster taken from $0206)",
     "solution": "N303 JSL ColosseumRangeCheck: colosseum iff $23E <= id < $240; btlgfx checks (C1 sprite.asm cpx #$023E/#$023F, init.asm cpx #$023F) are exact compares and stay",
     "patch_points": [{"snes": "C22F75", "pc": "022F75", "expected": "AE D4 3E E0 3E 02", "new": "22 20 12 F0 EA EA"}]},
    {"dependency": "RAGE_LEARNING", "class": "excluded-by-engine",
     "where": "LearnRage C2:4A09 'LDA $2002,X / BNE' skips monster IDs >= $100; MonsterRage CF:4600 256x2; rage bits $1D2C (SRAM, 256 bits); rage list C2:5837-5863 (8-bit ids 0-$FE)",
     "nine_bit_ids_work_in_place": False,
     "solution": "policy: new monsters ($180+) never become Gau Rages - already guaranteed by the vanilla guard (asserted by the builder, untouched); no vanilla Rage changed; no SRAM change",
     "patch_points": [{"snes": "C24A09", "pc": "024A09", "expected": "BD 02 20 D0 0F", "new": "unchanged (asserted)"}]},
    {"dependency": "VELDT_REGISTRATION", "class": "excluded-by-engine + builder flag",
     "where": "battle end C2:49E3 ($2F4B bit1 'can't appear on Veldt'), C2:49E9 (monster id >= $100 skip), battle id >= $200 skip; Veldt formation bits $1DDD",
     "nine_bit_ids_work_in_place": False,
     "solution": "new formations never registered: formation id >= $200 and monster id >= $100 both skip; builder additionally forces aux byte 3 bit1 for every formation with an id >= $100",
     "patch_points": [{"snes": "C249E3", "pc": "0249E3", "expected": "89 02 D0 1F", "new": "unchanged (asserted)"},
                      {"snes": "C249E9", "pc": "0249E9", "expected": "BD 02 20 D0 14", "new": "unchanged (asserted)"}]},
    {"dependency": "MONSTER_PALETTES", "class": "not-relocated",
     "where": "MonsterPal D2:7820 (0x3000 bytes = 768 x 16-byte units)", "indexed_by": "10-bit palette index in gfx prop bytes 2-3, not monster ID",
     "nine_bit_ids_work_in_place": True,
     "solution": "new monsters reference vanilla palette units (QA: 0x027, 0x04A); NEW palettes need a later relocation (consumers in btlgfx) or audited free units - not needed for v0.5"},
    {"dependency": "MONSTER_GRAPHICS", "class": "not-relocated",
     "where": "MonsterGfx E9:7000 (tile data; offset*8 from gfx prop, window to ED:6FF8), stencils D2:A824/D2:AC24",
     "indexed_by": "graphics offset / stencil index in gfx prop", "nine_bit_ids_work_in_place": True,
     "solution": "QA reuses vanilla graphics; final art needs a graphics-data allocation (base immediates C1:2102/2108/210E) - out of scope"},
    {"dependency": "METAMORPH", "class": "not-relocated", "where": "MetamorphProp C4:7F40",
     "indexed_by": "metamorph set id in MonsterProp byte 0x1A (per-monster record, relocated with MONSTER_PROP)", "nine_bit_ids_work_in_place": True,
     "solution": "no change"},
    {"dependency": "RAGE_PROPERTIES", "class": "not-relocated", "where": "MonsterRage CF:4600, InitRage C4:7AA0",
     "indexed_by": "rage id (8-bit)", "nine_bit_ids_work_in_place": False,
     "solution": "excluded (see RAGE_LEARNING); low-risk Rage expansion report in MONSTER_DEPENDENCY_AUDIT_v0.5.md section 6"},
    {"dependency": "COLOSSEUM_OPPONENTS", "class": "not-relocated", "where": "ColosseumProp DF:B600 (monster byte), MonsterAlign EC:E800 (256)",
     "indexed_by": "item id -> 8-bit monster id", "nine_bit_ids_work_in_place": False,
     "solution": "new monsters cannot be colosseum opponents (not required); colosseum battles $23E/$23F unchanged"},
    {"dependency": "ENCOUNTER_PACKS", "class": "engine-native",
     "where": "RandBattleGroup CF:4800, WorldBattleGroup CF:5400, SubBattleGroup CF:5600 (16-bit formation ids, bit15 = +rand 0..3)",
     "nine_bit_ids_work_in_place": True, "solution": "formations $240-$3FF can be referenced directly; no change"},
    {"dependency": "EVENT_BATTLE_GROUPS", "class": "engine-native",
     "where": "EventBattleGroup CF:5000 (256 groups x 2 x 16-bit formation ids; event cmd $4D 8-bit group)",
     "nine_bit_ids_work_in_place": True,
     "solution": "groups $9A-$FF are 00 00 00 00 and unreferenced (audit); QA uses group $FE (monster-tech only)"},
    {"dependency": "MAGIC_POINTS", "class": "limitation", "where": "battle win C2:5D94 LDX wBattleID / C2:5D97 CPX #$0200 / BCS + BattleMagicPoints DF:B400 (512)",
     "indexed_by": "battle id", "nine_bit_ids_work_in_place": False,
     "solution": "formations >= $200 award 0 magic points (vanilla behaviour for $200-$23F). Production normal encounters in $240+ will need a magic-points extension - REPORTED, not changed in v0.5"},
    {"dependency": "HARD_CODED_MONSTER_IDS", "class": "engine-native",
     "where": "Ghost Train $106 exact compares (btlgfx train_gfx C1:B532, monster_gfx); battle ids $1CF (Doom Gaze), $1D7 (final battle), $1E5 (Terra vs soldiers), $23E/$23F exact",
     "nine_bit_ids_work_in_place": True, "solution": "exact compares - unaffected by new IDs/formations"},
    {"dependency": "LOOP_BOUNDS", "class": "engine-native",
     "where": "InitMonsters / LoadBattleProp / btlgfx init loop over 6 slots, not over monster IDs",
     "nine_bit_ids_work_in_place": True, "solution": "no change"},
    {"dependency": "MONSTER_DIALOGUE", "class": "not-relocated", "where": "MonsterDlgPtrs CF:DFE0, MonsterDlg CF:E1E0",
     "indexed_by": "message id from AI script", "nine_bit_ids_work_in_place": True, "solution": "no change (QA AI uses no dialogue)"},
    {"dependency": "SRAM", "class": "engine-native",
     "where": "save data $1600-$1FFF: no monster ids stored; rage bits $1D2C (256), Veldt formation bits $1DDD (battle < $200)",
     "nine_bit_ids_work_in_place": True, "solution": "no SRAM change"},
    {"dependency": "EDITOR_ASSUMPTIONS", "class": "tooling",
     "where": "third-party editors assume 384 monsters / 576 formations at the vanilla addresses",
     "nine_bit_ids_work_in_place": False,
     "solution": "project sources (monsters/, formations/) + builder are authoritative; vanilla-address editing of monster tables in a v0.5+ ROM has no effect (tables relocated)"},
]

if __name__ == "__main__":
    out = {"_comment": "TECH v0.5 monster-ID dependency table (machine-readable). Rev 1 addresses. Generated by devtools/monster_dependency_table.py.",
           "id_ranges": {"vanilla": "000-17F", "new": "180-1FE", "null": "1FF"},
           "formation_ranges": {"vanilla": "000-23F", "colosseum": "23E-23F", "new": "240-3FF"},
           "dependencies": relocated() + MANUAL}
    p = os.path.join(HERE, "audits", "MONSTER_DEPENDENCY_TABLE_v0.5.json")
    json.dump(out, open(p, "w"), indent=1)
    print(p, len(out["dependencies"]), "dependencies,", sum(len(d.get("consumers", [])) for d in out["dependencies"]), "consumer patch points")
