#!/usr/bin/env python3
"""Dev-only: monster-ID dependency audit from the Rev 1 disassembly debug info.
Writes audits/monster_consumers_v0.5.json (evidence) and data/monster_relocation_v05.json
(builder input: exact consumer instructions + operand kind). usage: <ff6dis> <clean.sfc>"""
import sys, os, json
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "devtools"))
from dbgrefs import Dbg
dis, romp = sys.argv[1], sys.argv[2]
rom = open(romp, "rb").read()
D = Dbg(os.path.join(dis, "build/en/rom/ff6-en.dbg"))
# relocated tables: name -> (symbols, old base, end, record size, vanilla count)
REL = {
 "MONSTER_PROP":         (["MonsterProp"], 0xCF0000, 0xCF2FFF, 32, 384),
 "MONSTER_ITEMS":        (["MonsterItems"], 0xCF3000, 0xCF35FF, 4, 384),
 "MONSTER_OVERLAP":      (["MonsterOverlap"], 0xCF3600, 0xCF377F, 1, 384),
 "MONSTER_SPECIAL_ANIM": (["MonsterSpecialAnim"], 0xCF37C0, 0xCF393F, 1, 384),
 "MONSTER_CONTROL":      (["MonsterControl"], 0xCF3D00, 0xCF42FF, 4, 384),
 "MONSTER_SKETCH":       (["MonsterSketch"], 0xCF4300, 0xCF45FF, 2, 384),
 "MONSTER_NAME":         (["MonsterName"], 0xCFC050, 0xCFD0CF, 10, 384),
 "MONSTER_SPECIAL_NAME": (["MonsterSpecialName"], 0xCFD0D0, 0xCFDFDF, 10, 384),
 "AI_SCRIPT_PTRS":       (["AIScriptPtrs"], 0xCF8400, 0xCF86FF, 2, 384),
 "AI_SCRIPT":            (["AIScript"], 0xCF8700, 0xCFC04F, 1, None),
 "MONSTER_GFX_PROP":     (["MonsterGfxProp"], 0xD27000, 0xD2781F, 5, 416),
 "FORMATION_PROP":       (["BattleProp"], 0xCF5900, 0xCF61FF, 4, 576),
 "FORMATION_MONSTERS":   (["BattleMonsters"], 0xCF6200, 0xCF83FF, 15, 576),
}
LONG = {0xAF, 0xBF, 0x8F, 0x9F, 0xCF, 0xDF, 0x2F, 0x3F, 0x0F, 0x1F, 0x4F, 0x5F, 0x6F, 0x7F, 0xEF, 0xFF}
evidence, data = {}, {"_comment": "Generated by devtools/monster_consumer_audit.py; asserted against the clean ROM by the builder.", "tables": {}}
for name, (syms, base, end, rec, cnt) in REL.items():
    cons = []
    for nm in syms:
        for s in D.syms_by_name[nm]:
            for r in s.get("ref", "").split("+"):
                if not r: continue
                lid = int(r); f, ln, txt = D.line_src(lid)
                if not any(f.startswith(p) for p in ("src/battle/", "src/btlgfx/", "src/menu/", "src/field/", "src/world/", "./src/battle/", "./src/btlgfx/", "./src/menu/")):
                    continue
                if f.endswith(("battle_prop.asm",)) or "ai_script.asm" in f or "monster_text" in f:
                    continue
                for a, n in D.line_addrs(lid):
                    b = rom[a - 0xC00000:a - 0xC00000 + n]
                    if n == 4 and b[0] in LONG:
                        op = b[1] | b[2] << 8 | b[3] << 16
                        kind, disp = "long", op - base
                        assert base <= op <= end + 16, (name, hex(a))
                    elif "#^" in txt.replace(" ", "") or "lda#^" in txt.replace(" ", ""):
                        kind, disp = "imm_bank", 0
                        assert b[1] == base >> 16, (name, hex(a))
                    elif "#near" in txt or ".loword" in txt:
                        kind = "imm_near"; v = b[1] | b[2] << 8; disp = v - (base & 0xFFFF)
                        assert 0 <= disp < 0x100, (name, hex(a))
                    elif "wTargetProp" in txt or "near w" in txt:
                        continue                         # RAM struct member with the same name (not a ROM ref)
                    else:
                        raise SystemExit(f"unclassified ref {name} {a:06X} {txt}")
                    e = {"snes": f"{a:06X}", "bytes": b.hex(" ").upper(), "kind": kind, "disp": disp}
                    cons.append(e)
                    evidence.setdefault(name, []).append(dict(e, src=f"{f.lstrip('./')}:{ln}", text=txt))
    cons.sort(key=lambda e: e["snes"])
    data["tables"][name] = {"old_base": f"{base:06X}", "old_end": f"{end:06X}", "record_size": rec,
                            "vanilla_count": cnt, "consumers": cons}
json.dump({"tables": evidence, "counts": {k: len(v) for k, v in evidence.items()}},
          open(os.path.join(HERE, "audits", "monster_consumers_v0.5.json"), "w"), indent=1)
json.dump(data, open(os.path.join(HERE, "data", "monster_relocation_v05.json"), "w"), indent=1)
print({k: len(v["consumers"]) for k, v in data["tables"].items()})
