#!/usr/bin/env python3
"""DEV-ONLY (TECH v0.7.1): evidence for the three vanilla padding claims (ITEMX_C0/C2/C3_STUBS).

For each gap, from the clean ROM and the byte-identical Rev 1 disassembly (everything8215/ff6 ROM_VERSION=1):
  all_FF                 every byte of the gap is $FF in the clean ROM
  segments_overlapping   ld65 segments (code AND data: jump tables, text, graphics) that overlap the gap -> must be []
  instructions_inside    Rev 1 instructions starting inside the gap -> must be 0
  control_or_long_refs   JMP/JSR (abs, (abs), (abs,X)) in the same bank or any long operand (LDA f:, JSL, JML, ...)
                         that addresses the gap -> must be []
Data abs operands are DB-relative (WRAM banks $7E/$7F in these engines) and cannot address ROM padding.
usage: vanilla_claims_v071.py <clean.sfc> <insn.tsv> <ff6-en.dbg> <out.json>"""
import json, re, sys

GAPS = [("ITEMX_C0_STUBS", 0xC0D613, 0xC0DF9F, 0xC0D620, 0xC0DF8F),
        ("ITEMX_C2_STUBS", 0xC26469, 0xC267FF, 0xC26470, 0xC267FF),
        ("ITEMX_C3_STUBS", 0xC3F091, 0xC3FFFF, 0xC3F0A0, 0xC3FFEF)]


def main(rom, tsv, dbg, out):
    clean = open(rom, "rb").read()
    rows = [l.rstrip("\n").split("\t") for l in open(tsv)]
    segs = []
    for l in open(dbg):
        if l.startswith("seg\t"):
            kv = dict(re.findall(r'(\w+)=("[^"]*"|[^,]+)', l.split("\t", 1)[1]))
            st, sz = int(kv["start"], 16), int(kv["size"], 16)
            if sz:
                segs.append((kv["name"].strip('"'), st, st + sz - 1))
    res = {"_comment": "Generated by devtools/vanilla_claims_v071.py", "segments_total": len(segs)}
    for n, g0, g1, c0, c1 in GAPS:
        allff = all(b == 0xFF for b in clean[g0 & 0x3FFFFF:(g1 & 0x3FFFFF) + 1])
        over = [f"{s}:{a:06X}-{b:06X}" for s, a, b in segs if a <= g1 and b >= g0]
        inside = [r[0] for r in rows if g0 <= int(r[0].replace(":", ""), 16) <= g1]
        refs = []
        for r in rows:
            if not r[4]:
                continue
            v, bank = int(r[4], 16), int(r[0][:2], 16)
            if r[3] in ("absl", "abslx"):
                a = v
            elif r[2] in ("JMP", "JSR") and r[3] in ("abs", "absi", "absix"):
                a = (bank << 16) | v
            else:
                continue
            if g0 <= a <= g1:
                refs.append(r[0])
        before = [f"{s}:{a:06X}-{b:06X}" for s, a, b in segs if b < g0 and b >= g0 - 0x40]
        after = [f"{s}:{a:06X}-{b:06X}" for s, a, b in segs if a > g1 and a <= g1 + 0x40]
        res[n] = {"gap": f"{g0:06X}-{g1:06X}", "claim": f"{c0:06X}-{c1:06X}", "all_FF": allff,
                  "segments_overlapping": over, "segment_ending_before": before, "segment_starting_after": after,
                  "instructions_inside": len(inside), "control_or_long_refs": refs}
        ok = allff and not over and not inside and not refs
        print(n, "PASS" if ok else "FAIL", res[n])
    json.dump(res, open(out, "w"), indent=1)


if __name__ == "__main__":
    main(*sys.argv[1:5])
