#!/usr/bin/env python3
"""TECH v0.9.2 generated documents (from the built ROMs / manifests and the source data; nothing hand-typed):

  HASHES_v0.9.2.txt              SHA-1 / CRC32 / size of every v0.9.1 / v0.9.2 output + the frozen v0.9 ROMs
  PATCH_TABLE_v0.9.2.md          vanilla-space patches and expansion placements that are NEW relative to the frozen
                                 v0.9 build of the same target (production / celes-tech v0.9.1, QA v0.9.2)
  out/DELTA_v0.9_to_v0.9.2.csv   byte ranges that differ (v0.9.1 production vs v0.9 production, v0.9.2 QA vs v0.9 QA)
  ITEM_ALIGNMENT_v0.9.1.md       per item: locked source / v0.9 / v0.9.1 (consumables, shops, equipment, key items)

usage: docs_v092.py <out dir> <ff6x_tech dir>
"""
import csv, hashlib, json, os, sys, zlib

NEW = {"production": "FF6X_Rev1_TECH_v0.9.1_PRODUCTION", "celes-tech": "FF6X_Rev1_TECH_v0.9.1_CELES_TECH",
       "item-tech": "FF6X_Rev1_TECH_v0.9.2_ITEM_ALIGNMENT_CELES_ENABLERS_QA"}
OLD = {"production": "FF6X_Rev1_TECH_v0.9_PRODUCTION", "celes-tech": "FF6X_Rev1_TECH_v0.9_CELES_TECH",
       "item-tech": "FF6X_Rev1_TECH_v0.9_CONSUMABLE_RARE_QA"}


def h(p):
    b = open(p, "rb").read()
    return hashlib.sha1(b).hexdigest(), f"{zlib.crc32(b) & 0xFFFFFFFF:08X}", len(b)


def snes(pc):
    return f"{0xC0 + (pc >> 16):02X}:{pc & 0xFFFF:04X}"


def hashes(d, root):
    lines = ["# TECH v0.9.1 / v0.9.2 hashes (SHA-1, CRC32, size). Input: Final Fantasy III (USA) (Rev 1).sfc "
             "SHA-1 057ada1c641e3e0b3ca34e6e4f4eb1b05a87143a CRC32 C0FA0464"]
    for t, base in NEW.items():
        for ext in (".sfc", ".ips", ".bps", ".manifest.json", ".diff.csv", ".formation_safety.json"):
            p = os.path.join(d, base + ext)
            if os.path.exists(p):
                s, c, n = h(p)
                lines.append(f"{s}  {c}  {n}  {base + ext}")
    lines.append("# frozen TECH v0.9 (USER RUNTIME PASS / ACCEPTED) - reproduced byte-exact by this source")
    for base in OLD.values():
        s, c, n = h(os.path.join(d, base + ".sfc"))
        lines.append(f"{s}  {c}  {n}  {base}.sfc")
    open(os.path.join(root, "HASHES_v0.9.2.txt"), "w").write("\n".join(lines) + "\n")
    open(os.path.join(d, "HASHES_v0.9.2.txt"), "w").write("\n".join(lines) + "\n")


def patch_table(d, root):
    out = ["# PATCH TABLE - TECH v0.9.1 (production / celes-tech) and v0.9.2 (QA)", "",
           "Generated by `tools/docs_v092.py` from the build manifests. Lists only what is NEW relative to the frozen "
           "v0.9 build of the same target; everything else is byte-identical to the accepted v0.9 (see "
           "`out/DELTA_v0.9_to_v0.9.2.csv` for the exact byte ranges).", ""]
    rows = []
    for t, base in NEW.items():
        m = json.load(open(os.path.join(d, base + ".manifest.json")))
        o = json.load(open(os.path.join(d, OLD[t] + ".manifest.json")))
        old_ids = {(r["patch_id"], r["snes_start"]) for r in o["patches"]}
        newp = [r for r in m["patches"] if (r["patch_id"], r["snes_start"]) not in old_ids and r["kind"] == "vanilla_patch"]
        old_pl = {(p["label"], p["snes_start"]) for p in o["placements"]}
        newpl = [p for p in m["placements"] if (p["label"], p["snes_start"]) not in old_pl]
        out += [f"## {t} - `{base}.sfc`", "", f"SHA-1 `{m['identity']['sha1']}` CRC32 `{m['identity']['crc32']}`", "",
                "### Vanilla-space patches new in this build", "",
                "| patch id | SNES | bytes | original | new | consumer | reason |", "|---|---|---|---|---|---|---|"]
        for r in sorted(newp, key=lambda r: r["snes_start"]):
            out.append(f"| {r['patch_id']} | {r['snes_start']} | {r['length']} | `{r['expected_original'][:40]}` | "
                       f"`{r['new'][:40]}` | {r['consumer']} | {r['reason'][:140]} |")
        out += ["", "### Expansion placements new / changed in this build", "", "| region | label | SNES | patch id |",
                "|---|---|---|---|"]
        for p in sorted(newpl, key=lambda p: p["snes_start"]):
            out.append(f"| {p['region']} | {p['label']} | {p['snes_start']}-{p['snes_end']} | {p['patch_id']} |")
        out.append("")
        a = open(os.path.join(d, base + ".sfc"), "rb").read()
        b = open(os.path.join(d, OLD[t] + ".sfc"), "rb").read()
        i = 0
        while i < len(a):
            if a[i] != b[i]:
                j = i
                while j + 1 < len(a) and a[j + 1] != b[j + 1]:
                    j += 1
                rows.append([t, f"{i:06X}", f"{j:06X}", snes(i), snes(j), j - i + 1,
                             b[i:j + 1].hex(" ").upper() if j - i < 32 else "<long>",
                             a[i:j + 1].hex(" ").upper() if j - i < 32 else "<long>"])
                i = j + 1
            else:
                i += 1
    open(os.path.join(root, "PATCH_TABLE_v0.9.2.md"), "w").write("\n".join(out) + "\n")
    with open(os.path.join(d, "DELTA_v0.9_to_v0.9.2.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["target", "pc_start", "pc_end", "snes_start", "snes_end", "length", "v0.9", "new"])
        w.writerows(rows)


def alignment(root):
    j = lambda p: json.load(open(os.path.join(root, p)))
    c9 = {c["id"]: c for c in j("items/production_v09/consumables.json")["items"]}
    c91 = j("items/production_v091/consumables.json")["items"]
    out = ["# ITEM DATA ALIGNMENT - TECH v0.9.1", "",
           "Generated by `tools/docs_v092.py` from `items/production_v09` (accepted v0.9) and `items/production_v091` "
           "(this build). Decisions: `docs/design/DESIGN_DECISIONS_v1.0.md` (D-16 .. D-20); cross-check rows: "
           "`docs/design/V09_DATA_CROSSCHECK_v1.0.csv`. Item IDs, names and the save layout are unchanged.", "",
           "## Consumables $127-$12E", "",
           "| id | item | v0.9 effect | v0.9.1 effect | targeting | price / sold | change source |", "|---|---|---|---|---|---|---|"]
    for c in c91:
        o = c9[c["id"]]
        eff = lambda e: ", ".join(f"{k}={v}" for k, v in e.items())
        out.append(f"| ${c['id']} | {c['locked_name']} | {eff(o['effect'])} ({o['targeting']}) | {eff(c['effect'])} | "
                   f"{c['targeting']} | {c['price'] if c['sold_in_shops'] else 'not sold'}"
                   f"{' / cap ' + str(c['shop_cap']) if c.get('shop_cap') else ''} | "
                   f"{'; '.join(c.get('v091_changes', []))} |")
    out += ["", "Derived values (documented, conservative): " + "; ".join(
        f"**{c['locked_name']}**: " + " / ".join(c["derived"]) for c in c91 if c["id"] in ("127", "12B", "12E")), ""]
    out += ["## Reconstruction shops (Master Design Bible s19, D-18)", "", "| shop | name | type | entries |", "|---|---|---|---|"]
    for s in j("items/production_v091/ext_shops.json")["shops"]:
        out.append(f"| ${s['shop_id']} | {s['symbol']} | {s['type']} (price mod {s['price_mod']}) | {', '.join(s['items'])} - {s['note']} |")
    out += ["", "## Signature equipment changes", "", "| id | item | change |", "|---|---|---|"]
    for it in j("items/production_v091/equipment.json")["items"]:
        if it.get("v091_changes"):
            a = it["acquisition"]
            out.append(f"| ${it['id']} | {it['locked_name']} | {'; '.join(it['v091_changes'])} -> source `{a['source_type']}`: "
                       f"{a['planned_source']} ({', '.join(a['conditions'])}) |")
    out += ["", "## Key items (metadata only; the Triune Sigil description text changes)", "", "| rare id | item | change |",
            "|---|---|---|"]
    for r in j("items/production_v091/rare_items.json")["rare_items"]:
        out.append(f"| {r['rare_id']} | {r['locked_name']} | {'; '.join(r.get('v091_changes', []))} |")
    open(os.path.join(root, "ITEM_ALIGNMENT_v0.9.1.md"), "w").write("\n".join(out) + "\n")


if __name__ == "__main__":
    d, root = sys.argv[1], sys.argv[2]
    hashes(d, root)
    patch_table(d, root)
    alignment(root)
    print("written HASHES_v0.9.2.txt PATCH_TABLE_v0.9.2.md ITEM_ALIGNMENT_v0.9.1.md out/DELTA_v0.9_to_v0.9.2.csv")
