#!/usr/bin/env python3
"""TECH v0.9.3 generated documents (from the built ROMs / manifests; nothing hand-typed):

  HASHES_v0.9.3.txt              SHA-1 / CRC32 / size of the v0.9.3 QA outputs, the unchanged v0.9.1 production /
                                 celes-tech ROMs and the frozen v0.9 ROMs
  PATCH_TABLE_v0.9.3.md          what changed in the QA ROM relative to the v0.9.2 QA ROM (manifest patches and
                                 placements whose bytes differ, and every differing byte range with its region)
  out/DELTA_v0.9.2_to_v0.9.3.csv byte ranges that differ (v0.9.2 QA -> v0.9.3 QA)

usage: docs_v093.py <out dir> <ff6x_tech dir> <v0.9.2 QA .sfc (manifest next to it)>
"""
import csv, hashlib, json, os, sys, zlib

QA = "FF6X_Rev1_TECH_v0.9.3_VISUAL_STATE_VRAM_HOTFIX_QA"
UNCHANGED = ["FF6X_Rev1_TECH_v0.9.1_PRODUCTION", "FF6X_Rev1_TECH_v0.9.1_CELES_TECH"]
FROZEN = ["FF6X_Rev1_TECH_v0.9_PRODUCTION", "FF6X_Rev1_TECH_v0.9_CELES_TECH", "FF6X_Rev1_TECH_v0.9_CONSUMABLE_RARE_QA"]


def h(p):
    b = open(p, "rb").read()
    return hashlib.sha1(b).hexdigest(), f"{zlib.crc32(b) & 0xFFFFFFFF:08X}", len(b)


def snes(pc):
    return f"{0xC0 + (pc >> 16):02X}:{pc & 0xFFFF:04X}"


def hashes(d, root):
    lines = ["# TECH v0.9.3 hashes (SHA-1, CRC32, size). Input: Final Fantasy III (USA) (Rev 1).sfc "
             "SHA-1 057ada1c641e3e0b3ca34e6e4f4eb1b05a87143a CRC32 C0FA0464",
             "# QA ROM (the only ROM that changed in v0.9.3)"]
    for ext in (".sfc", ".ips", ".bps", ".manifest.json", ".diff.csv", ".formation_safety.json"):
        s, c, n = h(os.path.join(d, QA + ext))
        lines.append(f"{s}  {c}  {n}  {QA + ext}")
    lines.append("# v0.9.1 production / celes-tech - UNCHANGED by v0.9.3 (SHA-1 pinned in build.py)")
    for base in UNCHANGED:
        s, c, n = h(os.path.join(d, base + ".sfc"))
        lines.append(f"{s}  {c}  {n}  {base}.sfc")
    lines.append("# frozen TECH v0.9 (USER RUNTIME PASS / ACCEPTED) - reproduced byte-exact by this source")
    for base in FROZEN:
        s, c, n = h(os.path.join(d, base + ".sfc"))
        lines.append(f"{s}  {c}  {n}  {base}.sfc")
    for p in (os.path.join(root, "HASHES_v0.9.3.txt"), os.path.join(d, "HASHES_v0.9.3.txt")):
        open(p, "w").write("\n".join(lines) + "\n")


def patch_table(d, root, old):
    new_m = json.load(open(os.path.join(d, QA + ".manifest.json")))
    old_m = json.load(open(old.replace(".sfc", ".manifest.json")))
    a = open(os.path.join(d, QA + ".sfc"), "rb").read()
    b = open(old, "rb").read()
    runs = []
    i = 0
    while i < len(a):
        if a[i] != b[i]:
            j = i
            while j + 1 < len(a) and a[j + 1] != b[j + 1]:
                j += 1
            runs.append((i, j))
            i = j + 1
        else:
            i += 1

    def owner(m, pc):
        for p in m["placements"]:
            s0 = int(p["snes_start"].replace(":", ""), 16); e0 = int(p["snes_end"].replace(":", ""), 16)
            if s0 - 0xC00000 <= pc <= e0 - 0xC00000:
                return f"{p['region']} / {p['label']} ({p['patch_id']})"
        for p in m["patches"]:
            s0 = int(p["snes_start"].replace(":", ""), 16) - 0xC00000
            if s0 <= pc < s0 + p["length"]:
                return f"vanilla-space patch {p['patch_id']}"
        return "header / checksum / metadata"
    out = ["# PATCH TABLE - TECH v0.9.3 (visual state / VRAM hotfix, QA ROM only)", "",
           "Generated by `tools/docs_v093.py`. Compares the v0.9.3 QA ROM with the v0.9.2 QA ROM. Production / celes-tech "
           "v0.9.1 are byte-identical (SHA-1 pinned), the frozen v0.9 targets are byte-identical. No hook, engine routine "
           "or vanilla-space patch changed except the header checksum (P999): every other differing byte is in a "
           "QA-target expansion region - map palette $30 (MAPX_MAP_PAL), the enabler event package (E8 tiles; later "
           "events shift, so the trigger / NPC vector tables that point into it follow), the QA hub events (party "
           "normaliser) and its root dialogue, build metadata.", "",
           f"v0.9.2 QA SHA-1 `{hashlib.sha1(b).hexdigest()}` -> v0.9.3 QA SHA-1 `{new_m['identity']['sha1']}` "
           f"CRC32 `{new_m['identity']['crc32']}`", "",
           f"{len(runs)} differing byte runs, {sum(j - i + 1 for i, j in runs)} bytes.", "",
           "## Vanilla-space patches: new / changed / removed vs v0.9.2", ""]
    op = {(p["patch_id"], p["snes_start"], p.get("new")) for p in old_m["patches"] if p.get("kind") == "vanilla_patch"}
    np_ = {(p["patch_id"], p["snes_start"], p.get("new")) for p in new_m["patches"] if p.get("kind") == "vanilla_patch"}
    ch = sorted({(x[0], x[1]) for x in (np_ - op) | (op - np_)})
    out.append("none (identical set of vanilla-space patches, same bytes)" if not ch else
               "\n".join(f"* `{pid}` {sn} (bytes differ)" for pid, sn in ch))
    out += ["", "## Expansion placements whose bytes differ", "", "| patch id | SNES | v0.9.2 | v0.9.3 |", "|---|---|---|---|"]
    oe = {(p["patch_id"], p["snes_start"]): p.get("new") for p in old_m["patches"] if p.get("kind") != "vanilla_patch"}
    for p in new_m["patches"]:
        k = (p["patch_id"], p["snes_start"])
        if p.get("kind") != "vanilla_patch" and k in oe and oe[k] != p.get("new"):
            sh = lambda v: (v if len(str(v)) < 60 else str(v)[:57] + "...")
            out.append(f"| {p['patch_id']} | {p['snes_start']} | `{sh(oe[k])}` | `{sh(p.get('new'))}` |")
    out += ["", "## Differing byte runs by owner", "", "| owner | runs | bytes | first SNES | last SNES |", "|---|---|---|---|---|"]
    agg = {}
    for i, j in runs:
        o = owner(new_m, i)
        g = agg.setdefault(o, [0, 0, i, j])
        g[0] += 1; g[1] += j - i + 1; g[3] = j
    for o, (n, nb, f, l) in sorted(agg.items(), key=lambda x: x[1][2]):
        out.append(f"| {o} | {n} | {nb} | {snes(f)} | {snes(l)} |")
    out.append("")
    open(os.path.join(root, "PATCH_TABLE_v0.9.3.md"), "w").write("\n".join(out) + "\n")
    with open(os.path.join(d, "DELTA_v0.9.2_to_v0.9.3.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["pc_start", "pc_end", "snes_start", "snes_end", "length", "owner", "v0.9.2", "v0.9.3"])
        for i, j in runs:
            w.writerow([f"{i:06X}", f"{j:06X}", snes(i), snes(j), j - i + 1, owner(new_m, i),
                        b[i:j + 1].hex(" ").upper() if j - i < 32 else "<long>",
                        a[i:j + 1].hex(" ").upper() if j - i < 32 else "<long>"])
    return agg


if __name__ == "__main__":
    d, root, old = sys.argv[1], sys.argv[2], sys.argv[3]
    hashes(d, root)
    agg = patch_table(d, root, old)
    for k, v in agg.items():
        print(k, v[:2])
    print("written HASHES_v0.9.3.txt PATCH_TABLE_v0.9.3.md out/DELTA_v0.9.2_to_v0.9.3.csv")
