"""I1xx-I9xx - TECH v0.7.1 SIGNATURE EQUIPMENT BANK PROOF (extended item ids $100-$13F, Option C).

Builder-owned sources:
  asm/item_v071/*.s            65816 sources (ff6x/asm816.py, ca65-oracle checked)
  items/qa_v071/qa_items.json  QA-only extended equipment $13D-$13F (QA targets only)
  data/item_relocation_v071.json  Rev 1 consumer list of ItemProp / ItemName long operands (retargeted)
  patches/item_v071_hooks.py   exact hook table (generated by devtools/gen_hooks_v071.py; hooks noted in the manifest)

Tables (ITEMX_TABLES, FA:0000-FA:7FFF):
  XItemProp   FA:0000  320 x 30 B   ids $000-$13F ($000-$0FF byte-identical copy of D8:5000)
  XItemName   FA:2580  320 x 13 B   ids $000-$13F ($000-$0FF byte-identical copy of D2:B300)
  XExtFlags   FA:35C0   64 x 1 B    ext id $100+i: bit0 defined, bit1 spear (jump x2)
  XDescPtr    FA:3600   64 x 2 B    near pointers (bank FA) to menu-encoded descriptions, 0 = none
  XWeaponAnimFull FA:3800 256 x 8 B  weapon animation by animation number: $00-$BF = byte copy of EC:E400..
                                    (93 vanilla entries + the bytes that follow, so every vanilla index reads
                                    the same bytes), $C0-$FF = extended weapons $100-$13F
  XJumpAnim   FA:3700  256 x 1 B   Jump animation by index: byte copy of ItemJumpThrowAnim D1:0040 (index = item + 1,
                                    $FF = unarmed), $80-$BF = extended weapons $100-$13F (vanilla Jump reaches only
                                    weapon indices $01-$5B and $FF; asserted at build time)
  XDescText   FA:4000-  strings
Code: ITEMX_CODE FA:8000-FA:FFFF; same-bank stubs in audited vanilla padding (C0 / C2 / C3 claims).
"""
import json, os, re
from ff6x.asm816 import Program
from ff6x.hirom import snes_to_pc, fmt_snes

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASM = os.path.join(HERE, "asm", "item_v071")
SOURCES = ["core.s", "c0.s", "c3.s", "c2.s", "c1x.s"]

N_IDS = 0x140
VAN_PROP, VAN_NAME, VAN_ANIM = 0xD85000, 0xD2B300, 0xECE400
T_PROP, T_NAME, T_FLAGS, T_DPTR, T_ANIM, T_DTXT = 0xFA0000, 0xFA2580, 0xFA35C0, 0xFA3600, 0xFA3800, 0xFA4000
ANIM_EXT0 = 0xC0          # XWeaponAnimFull index of extended weapon $100 (C2 XC2_AnimId: $BF + low byte, then INC)
VAN_JUMP, T_JUMP = 0xD10040, 0xFA3700
JUMP_EXT0 = 0x80          # XJumpAnim index of extended weapon $100 (C1 XC1_JumpAnim: $80 + low byte)
T_END = 0xFA7FFF

MENU_CH = {}
for _i, _c in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"):
    MENU_CH[_c] = 0x80 + _i
MENU_CH.update({"/": 0xC0, "'": 0xC3, "-": 0xC4, ".": 0xC5, ",": 0xC6, "%": 0xCD})


def menu_encode(text, space):
    out = bytearray()
    i = 0
    while i < len(text):
        if text.startswith("{n}", i):
            out.append(0x01); i += 3; continue
        c = text[i]
        if c == " ":
            out.append(space)
        elif c in MENU_CH:
            out.append(MENU_CH[c])
        else:
            raise SystemExit(f"item text: unencodable {c!r} in {text!r}")
        i += 1
    return bytes(out)


def nib_signed(v):
    if not -7 <= v <= 7:
        raise SystemExit("stat boost out of range -7..7")
    return v if v >= 0 else 8 - v


def nib_evade(v):
    if v % 10 or not -50 <= v <= 50:
        raise SystemExit("evade/mblock must be a multiple of 10 in -50..50")
    return v // 10 if v >= 0 else 5 - v // 10


def load_defs(meta):
    defs = []
    for src in meta.get("ext_item_sources", []):
        d = json.load(open(os.path.join(HERE, src)))
        if d.get("qa") and not meta.get("qa_harness"):
            raise SystemExit(f"{src}: QA item definitions in a non-QA target")
        for it in d["items"]:
            it["_src"] = src
            it["_qa"] = bool(d.get("qa"))
            defs.append(it)
    ids = [int(it["id"], 16) for it in defs]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate extended item id")
    for it, i in zip(defs, ids):
        if not 0x100 <= i <= 0x13F:
            raise SystemExit(f"extended id {i:03X} outside $100-$13F")
        if it["_qa"] and not 0x13D <= i <= 0x13F:
            raise SystemExit("QA items must use $13D-$13F only")
        if not it["_qa"] and not 0x100 <= i <= 0x126:
            raise SystemExit(f"production item {i:03X} outside $100-$126 ($127-$13C reserve, $13D-$13F QA)")
    prod = [it for it in defs if not it["_qa"]]
    if prod:
        from patches import equipment_v08
        equipment_v08.validate(prod)
    return defs


ELEMENT = {"FIRE": 0x01, "ICE": 0x02, "LIGHTNING": 0x04, "POISON": 0x08, "WIND": 0x10, "HOLY": 0x20, "EARTH": 0x40, "WATER": 0x80}
STATUS12 = {"BLIND": 0x0001, "ZOMBIE": 0x0002, "POISON": 0x0004, "MAGITEK": 0x0008, "VANISH": 0x0010, "IMP": 0x0020,
            "PETRIFY": 0x0040, "DEAD": 0x0080, "CONDEMNED": 0x0100, "NEAR_FATAL": 0x0200, "IMAGE": 0x0400,
            "SILENCE": 0x0800, "BERSERK": 0x1000, "CONFUSE": 0x2000, "SAP": 0x4000, "SLEEP": 0x8000}
RELIC_EFFECT = {"ATLAS_ARMLET": (9, 0x01), "EARRING": (9, 0x02), "HP_PLUS_25": (9, 0x04), "HP_PLUS_50": (9, 0x08),
                "HP_PLUS_12": (9, 0x10), "MP_PLUS_25": (9, 0x20), "MP_PLUS_50": (9, 0x40), "MP_PLUS_12": (9, 0x80),
                "INC_STEAL_RATE": (11, 0x01), "INC_SKETCH_RATE": (11, 0x04), "INC_CONTROL_RATE": (11, 0x08),
                "MAX_HIT_RATE": (11, 0x10)}
WEAPON_FLAG = {"BUSHIDO": 0x02, "BACK_ROW": 0x20, "TWO_HAND": 0x40, "RUNIC": 0x80}
WEAPON_SPECIAL = {"NONE": 0, "STEAL": 1}          # ThiefKnife's special (ItemProp byte 27 high nibble = 1)
CHARS = ["Terra", "Locke", "Cyan", "Shadow", "Edgar", "Sabin", "Celes", "Strago", "Relm", "Setzer", "Mog", "Gau",
         "Gogo", "Umaro"]
CATEGORY_TYPE = {"weapon": 1, "armor": 2, "shield": 3, "helmet": 4, "relic": 5}
DESC_LINE_MAX = 28        # vanilla descriptions reach 32 characters per line; signature items stay within 28


def bits(names, table, what):
    v = 0
    for n in names:
        if n not in table:
            raise SystemExit(f"unknown {what} {n!r}")
        v |= table[n]
    return v


def equip_word(users):
    w = 0
    for u in users:
        if u not in CHARS:
            raise SystemExit(f"unknown character {u!r}")
        w |= 1 << CHARS.index(u)
    return w


def compose_v08(clean, it):
    """TECH v0.8 explicit record: every ItemProp byte comes from the item definition; the vanilla template only
    supplies the icon, the block graphic (byte 27 low nibble), the weapon targeting byte and the weapon animation."""
    pc = lambda s: snes_to_pc(s)
    tpl = int(it["template"], 16)
    t = clean[pc(VAN_PROP) + 30 * tpl:pc(VAN_PROP) + 30 * tpl + 30]
    typ = CATEGORY_TYPE[it["category"]]
    if t[0] & 7 != typ:
        raise SystemExit(f"{it['id']}: template ${tpl:02X} is not a {it['category']}")
    rec = bytearray(30)
    rec[0] = typ                                        # usage bits clear: not throwable / not usable as an item
    w = equip_word(it["users"])
    rec[1], rec[2] = w & 0xFF, w >> 8                   # no MERIT / IMP flag: the locked users only
    imm = bits(it.get("immune_status", []), STATUS12, "status")
    rec[6], rec[7] = imm & 0xFF, imm >> 8
    for n in it.get("relic_effects", []):
        if n not in RELIC_EFFECT:
            raise SystemExit(f"{it['id']}: unknown relic effect {n}")
        o, b = RELIC_EFFECT[n]
        rec[o] |= b
    rec[16] = nib_signed(it["vigor"]) | nib_signed(it["speed"]) << 4
    rec[17] = nib_signed(it["stamina"]) | nib_signed(it["mag_pwr"]) << 4
    rec[20] = it["power"]
    rec[26] = nib_evade(it["evade"]) | nib_evade(it["mblock"]) << 4
    rec[28], rec[29] = 2, 0                             # vanilla price of unsold items; Sell excludes $1xx anyway
    if typ == 1:
        rec[14] = t[14]                                 # weapon targeting (single enemy, as every vanilla weapon)
        rec[15] = bits(it.get("elem_attack", []), ELEMENT, "element")
        rec[19] = bits(it.get("weapon_flags", []), WEAPON_FLAG, "weapon flag")
        rec[21] = it["hit_rate"]
        sp = it.get("weapon_special", "NONE")
        if sp not in WEAPON_SPECIAL:
            raise SystemExit(f"{it['id']}: unknown weapon special {sp}")
        rec[27] = (t[27] & 0x0F) | WEAPON_SPECIAL[sp] << 4
    else:
        rec[15] = bits(it.get("elem_half", []), ELEMENT, "element")
        rec[21] = it["mdef"]
        rec[22] = bits(it.get("elem_absorb", []), ELEMENT, "element")
        rec[23] = bits(it.get("elem_null", []), ELEMENT, "element")
        rec[24] = bits(it.get("elem_weak", []), ELEMENT, "element")
        rec[27] = t[27] & 0x0F if typ == 3 else 0       # shield block graphic / block type
    return bytes(rec)


def check_text_v08(it):
    nm = menu_encode(it["display_name"], 0xFE)
    if len(nm) > 12:
        raise SystemExit(f"{it['id']}: display name {it['display_name']!r} longer than 12")
    lines = it["desc"].split("{n}")
    if len(lines) > 2 or any(len(l) > DESC_LINE_MAX for l in lines):
        raise SystemExit(f"{it['id']}: description must be <= 2 lines of <= {DESC_LINE_MAX} characters")
    menu_encode(it["desc"], 0xFF)


def build_tables(clean, defs):
    pc = lambda s: snes_to_pc(s)
    prop = bytearray(clean[pc(VAN_PROP):pc(VAN_PROP) + 256 * 30]) + bytes(64 * 30)
    name = bytearray(clean[pc(VAN_NAME):pc(VAN_NAME) + 256 * 13]) + b"\xFF" * (64 * 13)
    flags = bytearray(64)
    dptr = bytearray(64 * 2)
    anim = bytearray(clean[pc(VAN_ANIM):pc(VAN_ANIM) + ANIM_EXT0 * 8]) + bytes(64 * 8)
    jump = bytearray(clean[pc(VAN_JUMP):pc(VAN_JUMP) + 0x100])
    for v in range(256):          # vanilla Jump indices must stay outside the extended block $80-$BF
        if clean[pc(VAN_PROP) + 30 * v] & 7 == 1 and JUMP_EXT0 <= v + 1 < JUMP_EXT0 + 0x40:
            raise SystemExit(f"vanilla weapon {v:02X} would collide with the extended Jump block")
    dtxt = bytearray()
    notes = {}
    for it in defs:
        i = int(it["id"], 16); k = i - 0x100
        v08 = "category" in it                         # TECH v0.8 explicit-field definition
        b = int(it["template"] if v08 else it["base"], 16)
        if v08:
            check_text_v08(it)
            rec = bytearray(compose_v08(clean, it))
        else:
            rec = bytearray(clean[pc(VAN_PROP) + 30 * b:pc(VAN_PROP) + 30 * b + 30])
        if it.get("clear_effects"):
            for o in list(range(3, 14)) + [15, 18, 19] + list(range(22, 26)):
                rec[o] = 0
        f = {} if v08 else it.get("fields", {})
        if "equip_chars" in f or "equip_flags" in f:
            w = int(f.get("equip_chars", "0"), 16) | int(f.get("equip_flags", "0"), 16)
            rec[1], rec[2] = w & 0xFF, w >> 8
        if "power" in f: rec[20] = f["power"]
        if "hit_rate" in f: rec[21] = f["hit_rate"]
        for key, o, sh in (("strength", 16, 0), ("speed", 16, 4), ("stamina", 17, 0), ("mag_pwr", 17, 4)):
            if key in f:
                rec[o] = (rec[o] & (0xF0 >> sh)) | (nib_signed(f[key]) << sh)
        if "evade" in f: rec[26] = (rec[26] & 0xF0) | nib_evade(f["evade"])
        if "mblock" in f: rec[26] = (rec[26] & 0x0F) | (nib_evade(f["mblock"]) << 4)
        if "price" in f: rec[28], rec[29] = f["price"] & 0xFF, f["price"] >> 8
        prop[30 * i:30 * i + 30] = rec
        icon = clean[pc(VAN_NAME) + 13 * b]
        nm = menu_encode(it["display_name"] if v08 else it["name"], 0xFE)
        if len(nm) > 12:
            raise SystemExit(f"{it['id']}: name longer than 12")
        name[13 * i:13 * i + 13] = bytes([icon]) + nm + b"\xFF" * (12 - len(nm))
        typ = rec[0] & 7
        if typ in (1, 3) and (rec[1] | rec[2] << 8) & 0x2800:
            # Gau's Rage (C2:0610 SetRage) and Umaro overwrite the battle hand ids; vanilla never lets them hold a
            # weapon or shield, and an extended hand item would misdirect the extended-hand checks (I530-I533)
            raise SystemExit(f"{it['id']}: extended weapon/shield must not be equippable by Gau ($0800) or Umaro ($2000)")
        if it.get("spear") and not (typ == 1 and (not v08 or it["family"] == "spear")):
            raise SystemExit(f"{it['id']}: spear flag (Jump x2) on a non-spear")
        flags[k] = 0x01 | (0x02 if it.get("spear") else 0)
        if typ == 1:
            wb = int(it.get("weapon_anim_from", it["template"] if v08 else it["base"]), 16)
            a = pc(VAN_ANIM) + 8 * (wb + 1)
            anim[8 * (ANIM_EXT0 + k):8 * (ANIM_EXT0 + k) + 8] = clean[a:a + 8]
            jump[JUMP_EXT0 + k] = clean[pc(VAN_JUMP) + wb + 1]
        txt = menu_encode(it["desc"], 0xFF) + b"\x00"
        dptr[2 * k:2 * k + 2] = ((T_DTXT + len(dtxt)) & 0xFFFF).to_bytes(2, "little")
        dtxt += txt
        notes[f"{i:03X}"] = {"name": it["display_name"] if v08 else it["name"], "base": it["template"] if v08 else it["base"],
                             "type": typ, "prop": rec.hex(" ").upper(),
                             "name_bytes": name[13 * i:13 * i + 13].hex(" ").upper(), "flags": f"{flags[k]:02X}",
                             "weapon_anim": anim[8 * (ANIM_EXT0 + k):8 * (ANIM_EXT0 + k) + 8].hex(" ").upper() if typ == 1 else None,
                             "jump_anim": f"{jump[JUMP_EXT0 + k]:02X}" if typ == 1 else None,
                             "source": it["_src"]}
    if T_DTXT + len(dtxt) - 1 > T_END:
        raise SystemExit("ITEMX_TABLES full")
    return [("XItemProp", T_PROP, bytes(prop)), ("XItemName", T_NAME, bytes(name)), ("XExtFlags", T_FLAGS, bytes(flags)),
            ("XDescPtr", T_DPTR, bytes(dptr)), ("XWeaponAnimFull", T_ANIM, bytes(anim)), ("XJumpAnim", T_JUMP, bytes(jump)), ("XDescText", T_DTXT, bytes(dtxt) or b"\x00")], notes


def table_externs():
    return {"XItemProp": T_PROP, "XItemName": T_NAME, "XExtFlags": T_FLAGS, "XDescPtr": T_DPTR,
            "XWeaponAnimFull": T_ANIM, "XJumpAnim": T_JUMP}


def load_source(asm_dir=None):
    src = []
    for f in SOURCES:
        p = os.path.join(asm_dir or ASM, f)
        if os.path.exists(p):
            src.append(f"; ==== {f}\n" + open(p).read())
    return "\n".join(src)


REGION_OF = {"XFA_CODE": ("place", "ITEMX_CODE"), "XC0": ("claim", "ITEMX_C0_STUBS"),
             "XC2": ("claim", "ITEMX_C2_STUBS"), "XC3": ("claim", "ITEMX_C3_STUBS")}


def hooks():
    from patches.item_v071_hooks import HOOKS
    return HOOKS


def retarget_tables(rom, patch_prefix):
    rel = json.load(open(os.path.join(HERE, "data", "item_relocation_v071.json")))
    n = 0
    for name, t in rel["tables"].items():
        new_base = int(t["new_base"], 16)
        old = int(t["old_base"], 16)
        for c in t["consumers"]:
            snes = int(c["snes"], 16)
            ins = bytes.fromhex(c["bytes"])
            if bytes(rom.clean[snes_to_pc(snes):snes_to_pc(snes) + len(ins)]) != ins:
                raise SystemExit(f"{name}: consumer bytes changed at {c['snes']}")
            if ins[1:] != (old + c["disp"]).to_bytes(3, "little"):
                raise SystemExit(f"{name}: operand mismatch at {c['snes']}")
            new = (new_base + c["disp"]).to_bytes(3, "little")
            rom.patch(snes + 1, ins[1:], new, f"{patch_prefix}_{name}",
                      consumer=f"{fmt_snes(snes)} {c['src']}",
                      reason=f"long operand {name}+{c['disp']} -> {fmt_snes(new_base)}+{c['disp']} (table relocated to 320 entries for 16-bit extended ids)",
                      retarget=True)
            n += 1
    return n


def build(rom, target, alloc, meta):
    defs = load_defs(meta)
    notes = {"ext_items": {}, "tables": {}, "sections": {}, "hooks": []}
    tables, notes["ext_items"] = build_tables(rom.clean, defs)
    for label, at, data in tables:
        rom.place("ITEMX_TABLES", data, label, "I101_ITEM_TABLES", at=at,
                  reason=f"{label}: extended item table (ids $000-$13F)",
                  consumer="retargeted ItemProp/ItemName consumers and TECH v0.7.1 routines")
        notes["tables"][label] = {"snes": fmt_snes(at), "length": len(data)}
    ext = table_externs()
    # engine source: frozen v0.7.x targets keep asm/item_v071 byte-for-byte; v0.8 targets use asm/item_v08
    # (same engine + the B-accumulator reset of KNOWN_RISKS_v0.8 R32)
    prog = Program(load_source(os.path.join(HERE, meta["engine_asm"]) if meta.get("engine_asm") else None), ext, "item_v071")
    secs = prog.assemble()
    for name, (org, code) in secs.items():
        how, reg = REGION_OF[name]
        if how == "place":
            rom.place(reg, code, f"{name}", "I102_ITEM_ENGINE_CODE", at=org,
                      reason="TECH v0.7.1 extended item engine (65816, asm/item_v071)",
                      consumer="JSL from hook sites / bank stubs")
        else:
            rom.patch(org, b"\xFF" * len(code), code, f"I103_{name}_STUBS", claim=reg,
                      consumer=f"JSR from same-bank hook sites ({name})",
                      reason="same-bank helper stubs in audited vanilla padding (never referenced, all $FF)")
        notes["sections"][name] = {"snes": fmt_snes(org), "length": len(code)}
    syms = dict(ext); syms.update(prog.symbols)
    notes["retargeted_operands"] = retarget_tables(rom, "I110_RETARGET")
    for h in hooks():
        site = int(h["snes"], 16)
        expect = bytes.fromhex(h["expect"])
        mode = h.get("mode", ".a8\n.i16")
        hp = Program(f".section H ${site:06X}\n{mode}\n{h['asm']}\n", syms, h["id"])
        new = hp.assemble()["H"][1]
        if len(new) < len(expect) and h.get("pad_nop"):
            new = new + b"\xEA" * (len(expect) - len(new))
        if len(new) != len(expect):
            raise SystemExit(f"{h['id']}: hook {len(new)} bytes vs expected original {len(expect)}")
        rom.patch(site, expect, new, h["id"], consumer=h["consumer"], reason=h["reason"])
        notes["hooks"].append({"id": h["id"], "snes": fmt_snes(site), "pc": f"{snes_to_pc(site):06X}",
                               "original": expect.hex(" ").upper(), "new": new.hex(" ").upper(),
                               "asm": h["asm"], "consumer": h["consumer"], "reason": h["reason"]})
    notes["symbols"] = {k: fmt_snes(v) for k, v in sorted(prog.symbols.items()) if v >= 0xC00000 and "@" not in k}
    notes["listing"] = {n: prog.listing(n) for n in secs}
    return notes
